### ISSUE TITLE
Create a dataset for "inequality" theme

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#103]
Create a dataset for historical households income in the US using data in Excel from US Census Bureau. The original data is here https://www2.census.gov/programs-surveys/cps/tables/time-series/historical-income-households/h01ar.xls and we want it to clean/format/convert. E.g., it is CSV with consistent values in fields.

## Acceptance criteria

* [x] a dataset for `historical-income-households-us` published under core user in production

## Tasks

* [x] analyse the source data [0.5h]
* [x] create `datapackage.json` [0.5h]
* [x] create `flow.yaml` [4h]
  * [x] get a table from a sheet
  * [x] clean data using dpp
* [x] write a tutorial [8h]
* [x] create views [1.5h]
* [x] publish under core [0.5h]

**Comment by anuveyatsu** [comment]
FIXED - http://datahub.io/core/historical-income-households-us
Tutorial is in appripriate hackmd
