### ISSUE TITLE
Create a dataset for "usa-education-budget"

### ISSUE THREAD

**Issue by Mikanebu** [datahq/pm#104]
Create a dataset for United States of America Education budget spendings comparing to GDP.

## Acceptance criteria

* [x] a dataset for usa-education-budget-analysis published under core user in production

## Tasks

* [x] Data processing:
  * [x] Download budget data from [here](https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/budget/fy2018/hist05z2.xls)
  * [x] Find dataset for GDP of USA with historic information
  * [x] In a new spreadsheet, add a row per year (2011-2020), with these columns:
    * [x] Extract total amount allocated for education from budget files
    * [x] GDP of USA
    * [x] ratio of the two (i.e. education expenditure / GDP)
  * [x] upload to DataHub
* [x] write a analysis [2h]
* [x] create views [1.5h]
* [x] publish under core [0.5h]

**Comment by Mikanebu** [comment]
FIXED, it is live under core https://datahub.io/core/usa-education-budget-analysis
