### ISSUE TITLE
Blog post re processing steps and versioning of datasets

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#105]
Write a blog post about processing steps - processing, succeeded and failed. Explain each step and also write about revisions.

## Acceptance criteria

* [x] a blog post published in the `/blog` page

## Tasks

* [x] plan
* [x] write a draft
* [x] add screenshots and gifs
* [x] review by another team member
* [x] refactor
* [x] publish

**Comment by anuveyatsu** [comment]
FIXED - http://datahub.io/blog/improved-reporting-and-debugging-of-data-publishing
