### ISSUE TITLE
Linux and Windows versions of data CLI

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#106]
We already have Linux version of the CLI, however, it has a problem with `opn` package. This was reported to `pkg` maintainers as it should be fixed there. They've reported that it's fixed now in https://github.com/zeit/pkg/releases/tag/4.2.5 so we should use the latest version of `pkg`.

Research about building Windows version of the CLI.

## Acceptance criteria

* [x] I can get `linux` or `windows` versions of CLI app on `/download` page.

## Tasks

* [x] Re-package the CLI using `pkg@4.2.5` and pass it to Linux user (eg, Irakli) and verify `opn` module works from the box [0.5h] - still not working
* [x] Analyse about packaging Windows version of the CLI [~2h]
  * [x] take a look at `now-cli` - do they have Windows version and if so how they've implemented it [0.5h]
  * [x] find more info from official docs [0.5h]
  * [x] search in existing issues on github [0.5h]
* [x] make changes in `package.json`, push and release new version of the CLI with all available OS versions [1h]

**Comment by anuveyatsu** [comment]
FIXED, see available versions of the CLI tool here https://datahub.io/download
