### ISSUE TITLE
Ensure npm/yarn installable

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#108]
We expect a lot of people to install the CLI tool using package managers such as npm/yarn. To provide them a nice experience we want to double check if everything works.

Notice, package name was changed recently, now it's called `data-cli` - check docs, blog posts and any other writings and update instructions.

## Accpetance criteria

* [ ] data CLI tool is published in the NPM here http://npmjs.com/package/data-cli
  * [ ] it has clear README about installation so I just copy paste it and run `data help` and it works
* [ ] I can install and start using data CLI tool with npm/yarn

## Tasks

* [ ] install and play with the tool using npm and yarn
  * [ ] do I have to use `-g` flag - if so update README so it is very clear
* [ ] try out on another OS, e.g., Linux
* [ ] update docs, blog post and other writings/instructions with a new name `data-cli` (old one was `datahub-cli`)

**Comment by zelima** [comment]
Issue moved to [datahq/data-cli #263](https://github.com/datahq/data-cli/issues/263) via [**ZenHub**](https://www.zenhub.com/)
