### ISSUE TITLE
[Epic] Marketing

### ISSUE THREAD

**Issue by zelima** [datahq/pm#114]
## Tasks

- [x] About page up with outline of product
- [ ] @rufus draft "data experience" post
- [ ] Publish data library design post on labs and datahub.io
- [x] Set up a helpdesk system
- [x] Split out docs and blog to a separate repo (?)
- [x] Tools page (?? vs download page ...)

**Comment by zelima** [comment]
FIXED. Don't think we are going to continue work on unticked items
