### ISSUE TITLE
[Epic] Purge datasets 

### ISSUE THREAD

**Issue by zelima** [datahq/pm#123]
As a Publisher, I want to permanently delete (purge) a data package so that it no longer takes up storage space. 

## Acceptance Criteria

* [ ] `data purge https://datahub.io/my/dataset` permanently deletes data from datahub.
* [ ] before delete asks me to type dataset name 
* [ ] ~~available button on showcase or publisher page?~~

## Tasks

* [x] Do analysis 
* [ ] Serve Delete API in specstore
  * [ ] Authorize
  * [ ] Delete from DB
  * [ ] Delete From S3
  * [ ] Delete from Elasticsearch
  * [ ] Tests
* [ ] Make request from CLI
  * [ ] Make sure to force user typing dataset name
  * [ ] Grab token from auth and make request to specstore
  * [ ] tests
* [ ] Test purge command via BB test for assembler (optional, but desirable)

### Possible ways to delete dataset

CLI and Web UI

* `data purge [identifier]`
  * ~~`data purge .`~~
  * ~~`data purg path/to/dataset`~~
  * `data purge https://datahub.io/my/dataset`
* ~~Button on showcase (probably not a good idea)~~
* ~~Button on publisher's page~~

Think we can hold on with Web UI in the beginning and go with CLI. (Though from user perspective it's more comfortable)

### How it's gonna work

Serve a DELETE endpoint in specstore API. Things to consider

* Authenticate user 
* Authorize - Make sure dataset belongs to the user
  * How this gonna happen? 
    * Check if user ID matches with dataset identifier

### What should we delete

* Pkgstore 
  * everything inside `pkgstore.datahub.io/publisher/[dataset-name]` folder on S3
* Specstore
  * Related entry from Dataset table
  * Related entries from Revisions table
* Metastore
  * related entry from `datahub` index `publisher-id/dataset-name`
  * I guess nothing from `evetnts` index, indeed export new event: delete
* ~~rawstore~~
  * how? - Probably use flow-spec contents to locate files (since they are located at filehash)

More about rawstore - not sure we should delete files from there as well. When pushing, we export files to rawstore under file hashes. So there might be another dataset using same exact file. That dataset might belong to same user or even another user.

Seem not a big deal - when another user will need to re-push we will re-export it, but On the other hand, file might be very large and re-uploading may result in decreasing push speed. But think not a big deal, they can wait.

But what about revisions? The publisher may have bunch other revisions of the same dataset and each revision may have its own data. There's no way right now to see the data from previous revisions. We either should include spec together with each revision or just forget about deleting files from rawstore. 

As a conclusion, I recommend not to purge files from rawstore.

### data purge in CLI

```javascript=
// data purg [identifier] optional if dataset in directory

// in cli
Promise.resolve().then(async () => {

  const dpJson = loadDpJson(path)
  const datasetName = dpJson.name

  let answer = prompt('You can make your dataset private, but if you are absolutely sure, please type dataset name (This action **cannot** be undone))

  if (answer === datasetName) {continue}

  datahub.client.purge(dataset)
}
                       
                       
// in client
const purge = dataset => {
  const token = authorize(jwt)
  const deleted = fetch api.specstoreDelete(urls, token, ownerid/dataset-name)

  if (delted.success) {console.log(deleted)}
}
```

### Delete API in specstore

```python=

def delete_(token, identifier):
  # Authoize user (make sure dataset belongs to user) to avoid security problems
  errors = []
  user_id = get_user_id(identifier)
  if not user_id == token.user_id:
    erros.append('not authorized')
    return  {success: False, errors: errors}
  specstore_success = delete_from_db(identifier)
  pkgstore_success = delete_from_s3(identifier)
  metastore_success = delete_from_es(identifier)
  return {success: specstore_success and pkgstore_success and metastore_success, errors: []}
```
