### ISSUE TITLE
[QA] Automate frontend related tests from QA spreadsheet

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#127]
Sections to be automated:

- Search page: 100-101, 103-106
- Dashboard page: 107-109
- Front page: 110-112
- Publisher page: 114-117

## Acceptance criteria

* [ ] the tests are automated and running on a weekly basis (on Thursday morning)

## Tasks

* [ ] analysis [0.5h]
* [ ] automate tests for Search page [2h]
* [ ] automate tests for Dashboard page [2.5h]
* [ ] automate tests for Front page [1h]
* [ ] automate tests for Publisher page [1.5h]
