### ISSUE TITLE
[Epic] 15 signups per day

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#129]
## Tasks

* [ ] Enable google login option 
* [ ] Separate `login` and `signup` buttons
* [ ] Say to people that to publish, they should login (On login page)
* [x] Start tracking clicks on `GitHub` button so we can compare that number against number of visitors of `/dashboard` page after `/login` page. So we can say that `x` users clicked on the button and only `y` of them successfully finished logging in.

**Comment by anuveyatsu** [comment]
@zelima should we close this epic?

**Comment by zelima** [comment]
@anuveyatsu we still did not hit the goal (15 signups daily). Though we completed all the tasks. Let's keep it until the end of the sprint
