### ISSUE TITLE
[Epic] People actually use downloaded CLI

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#130]
> This is probably the biggest issue we need to tackle:
> - Bad instructions and no tutorial (e.g. provide a sample dataset to upload)
> - Lack of login options (i.e. add Google)
> - More analytics in the CLI itself, track failures

**Goal: 50% of cli downloads < users with more than 0 pushes.**

## Tasks

* [x] track if it's the first time the app is run - https://github.com/datahq/data-cli/issues/322
* [x] prompt users to download the CLI tool in the `/dashboard` page - https://github.com/datahq/frontend/issues/243
* [x] once a user downloads the CLI provide extensive docs for getting started - place links on dashboard + download pages: https://github.com/datahq/frontend/issues/243
    * [x] installation docs should have separate sections for each OS and be more detailed (esp for windows) + should link to how to publish data docs: https://github.com/datahq/frontend/issues/242
    * [x] provide sample data file in publishing data docs - https://github.com/datahq/frontend/issues/244
      * [x] have GIF of the sample file being pushed
* [x] put GIF of pushing in the download page - https://github.com/datahq/frontend/issues/243
* [x] provide extensive docs for other commands such as `info, get and cat` - https://github.com/datahq/frontend/issues/245
* [x] improve README of https://github.com/datahq/data-cli - have in the README an explanation of what this is used for and some usage example (before the install, developers, configuration etc.)

## Analysis

Currently: 5 downloads 0 pushes

Some investigation:

I've analysed behaviour of newly signed up 20 users since 20th March. 

- 6 users login and visit their publisher page and that's all.
- 2 users donwload windows version of cli and run no command. This is possibly because they don't know how to run it.
- Most users login and do a lot of search or browse through website but don't download cli. They also download resources and usually visit some specific dataset page. Probably they think the page would have more stuff if they're authenticated.

However, not everyone who downloaded the cli is signed up.

## Q&A

* Why they download if not for push?
  * from new users in the last week (20-26 March) we can see that most users login but don't download the cli tool (probably they already have done it before login). Read above for more details.
* Did they login?
  * nobody logged in using cli (new users from last week)

Known problems:
- unauthenticated users behaviour are not unified (each command run is a separate session) so we aren't able to track his/her CLI usage until they logged in. We need to think how we can unify UID for them.

What's missing:
- tracking app's first run - it would be very useful, eg, use https://github.com/sindresorhus/first-run

**Comment by anuveyatsu** [comment]
@zelima should this issue be closed as part of previous sprint or current one?

**Comment by zelima** [comment]
FIXED in APR 9th milestone
