### ISSUE TITLE
[Epic] Marketing: datahub offers

### ISSUE THREAD

**Issue by zelima** [datahq/pm#131]
As a product owner, I want 3 core offers ready and up on datahub.io, so that my consumers/users have a clear understanding what we are offering and how we differ from others

## Acceptance Criteria

* [x] [Deploy] Core Data is on the front page by 3rd of April
* [x] [Data OS] Offer is drafted by 2nd of April
* [x] [Data MArt] Offer drafted (and combined with OS offer) by 9th of April
* [x] All 3 Offers are live by 20th of April

## Tasks

* [x] "Deploy" offer on front page @rufus/adam (on content) + @anu to implement - https://github.com/datahq/frontend/issues/257
* [x] "Data OS" offer up @adam
  * Tagline, one paragraph
  * List of features
  * Professional support
* [x] prepare "Consulting" aka "Data Mart" offering @adam + @rufus + @anu

**Comment by anuveyatsu** [comment]
FIXED:

* [x] deploy offer on front page
* [x] dataOS offer + basic page https://datahub.io/docs/data-os
* [x] consulting offer is on front page but the page itself is a placeholder for now
