### ISSUE TITLE
[Epic] Marketing: Newsletters, welcome emails and help desk

### ISSUE THREAD

**Issue by zelima** [datahq/pm#132]
High level User Stories:

As an Admin I want to boot up a newsletter system, so that my users can receive news about datahub updates. 

As an Admin I want to be able to send a welcome email whenever new user shows up, so that they know they become part of the team and feel welcome

As an Admin I want to boot up help desk system, so that my user get instant help, be able to satisfy their needs (Eg request specific data), or talk to sales people

## Acceptance Criteria

* [x] New users are receiving welcome emails once they sign-up
* [ ] All users (except unsubscribed) are receiving updates (of their choice?) about Datahub and it's products (Eg new core dataset)
* [x] We serve help desk for users
  * [ ] live chat
  * [x] Ticket system
  * [ ] Direct contact with sales (phone?)

## Tasks

* [x] Come up with lower level use stories for each item
* [x] Research and decide on help desk provider (See spreadsheet in drive)
  * https://freshdesk.com/
* [x] Research and decide on mail marketing provider 
  * https://mailchimp.com/
* [x] Do analysis
* [x] Boot up help Desk
* [x] Draft Welcome emails
  * [x] Reviewed by others
* [x] refactor Auth server to update List of users on mailchimp
  * [x] Create new module to handle mailing
  * [x] Updated envs (Mailchimp user/APIkeys)
  * [x] make sure Auth process does not terminate if something goes wrong there
* [x] Start sending Welcome Emails
  * [x] design and prepare welcome Email
  * [x] Review by designer
  * [x] Test it works
* [ ] Draft newsletter 
  * [ ] reviewed by others
* [ ] Process for adding new signups to newsletter list
  * [ ] Export user list from DB
  * [ ] Import list to mailchimp
  * [ ] design and prepare the newsletter Emails
  * [ ] review by designer
  * [ ] Test it works 
  * [ ] Make sure unsubscribe works

## Analysis

Continuew reading more detailed analysis but for both, welcome emails and newsletters we will use mailchimp rest API to populate List of subscriber. That's gonna happen from **Auth** service. Rest is taken care by mailchimp itself like scheduling, unsubscribe, mail design (we should do), etc...

__Big question remaining__: What should be the Email they get welcome and subscribed mails - support@datahub.io ?

ANSWER: will be sent from rufuspollok@datopian.com

### Welcome emails

As an admin I want to say welcome to my users and suggest where to start from, so that they can start using datahubs benefit's right away.

As an admin I want to tell datahub user about cool features (Eg core datasets, or popular datasets), so that they get more interested in using datahub

Tasks:

* [x] Find out if fleshdesk provides this service 
  * Apparently this has nothing to do with Flashdesk. At least I could not find any useful info on Flashdesk [name=Irakli]
  * Should we send Emails from Node application (or Auth?)
  * A: No fleshdesk is for ticketing system. We should go with mailchimp https://mailchimp.com/features/landing-pages/
* [x] How to connect our sign-up and sending email process?
  * A: mailchimp serves REST API. we can simply setup welcome email template there and hit the API to update the list of users (Email will be sent automatically)
  * Create an Automated Welcome Email: http://eepurl.com/c7VOa1
* [ ] Draft the Email

stuff to say in welcome email:

* welcome
* download app
* getting started 
* checkout some new datsets

### Newsletters

As Regular user I want to get news and updates about Datahub weekly or right away, So that I don't miss any new data

As a user, I want to be able to unsubscribe from newsletter, So that I don't recieve any news about datahub after I don't want it anymore

As a DataHub admin I want to keep my users updated with anything I've got new or interesting, So that I can increase their liability

As a DataHub admin, I want to be able to remove user from newsletter list, So that they don't get annoyed

As an admin I want to subscribe **all** my exiting users to the newsletters (until they unsubscribe), so that they I can remind them about datahub / see

As an admin I want to add **all** new users to newsletter list, so that all me new users get updated

Tasks

* [x] come up with userstories
* [x] Find the appropriate mail service
  * [ ] mailchimp, See alternatives for comparison https://docs.google.com/spreadsheets/d/16hPVEX16qd3bFPi9uoOnqPY3lcUePrcBOn9NSpDU6Fk/edit#gid=1496788358
* [ ] Draft the Email
* [ ] Design Email
* [ ] Decide on topics
* [ ] Decide how frequently to send

Stuff to discuss in newsletter:

* Most popular data
* New features
* Any other updates
* Use cases?

**Comment by zelima** [comment]
FIXED. Closing as much of this is done, followup about newsletters here https://github.com/datahq/pm/issues/148
