### ISSUE TITLE
[Epic] More core datasets

### ISSUE THREAD

**Issue by zelima** [datahq/pm#134]
As an Admin, I want more interesting and high-quality datasets, so that I can attract more users

## Acceptance Criteria

* [ ] we have more datasets from World Bank
* [ ] S&P data regularly scraping (daily)

## Tasks

* [ ] Research what datasets may be useful from the world bank
* [ ] Do analysis re S&P
* [ ] think of more core datasets
