### ISSUE TITLE
Blog post re datahub changes in Q1

### ISSUE THREAD

**Issue by zelima** [datahq/pm#135]
As an admin, I want to blog post about what's been done in the first quarter of 2018 and introduce our plans for next quarter, so that our users are up to date.

## Acceptance Criteria

* [x] blog post about Q1 exists on datahub 
* [ ] ~~blog post about changes: "from Data Publishing to Data Deployment"~~

## Tasks

* [x] draft the posts
* [x] review
* [x] publish

**Comment by anuveyatsu** [comment]
FIXED - https://datahub.io/blog/q1-2018-review
