### ISSUE TITLE
Datahub Python SDK

### ISSUE THREAD

**Issue by AcckiyGerman** [datahq/pm#137]
Continuing creating datahub SDK (original: https://github.com/datahq/pm/issues/133)

As an admin, I want to have Python SDK so that users can use datahub programmatically

As a user, I want to be able to write up a small code in Python to communicate with the Datahub, so that I'm able to publish or get datasets without manual interaction. 

## Acceptance Criteria

* [ ] Python SDK exists and well docmented
  * [ ] Has complete documentation
  * [ ] Tutorials, getting started etc...
  * [ ] blog Post

- [ ] blog Post about Python and JS SDK
* [ ] Track downloads of `datahub-client` and `datahub-client.py`

## Tasks

* [x] Common APIs defined
* [x] Write JS tutorial "Publish/Deploy Data on DataHub [with JS]" => changes @dima 
* [ ] Write same tutorial for python => list of requirements for python datahub-client-py (before even library exists)
* [ ] Write Python library 

# Analysis

## Define Common APIs
As a programmer I need APIs and docs to be able to:
- [x] Get data
- [x] Post data
- [ ] List my datasets
- [ ] (optional) Search for datasets

## Information sources
* Developers docs: https://docs.datahub.io/developers/api/
* Repositories docs:
    - https://github.com/datahq/auth#api
    - https://github.com/datahq/bitstore#api
    - https://github.com/datahq/specstore#api
    - https://github.com/datahq/metastore#api
* https://github.com/datahq/data-cli code itself

**Comment by AcckiyGerman** [comment]
Repository for the python library has been created: https://github.com/datahq/datahub-py
ATM it includes only the readme with specification in it.

**Comment by AcckiyGerman** [comment]
On hold
