### ISSUE TITLE
[Analytics] Consider using Google Tag Manager

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#139]
## Acceptance criteria

* [x] Analytics on datahub.io is operated via Google Tags Manager

## Tasks

* [x] analyse and explore how to use GTM
* [x] install GTM on datahub
* [x] remove GA from datahub and install it via GTM
* [x] test out using debug mode + Chrome extension for GTM
* [x] dashboard: setup triggering event with client used to login - web vs cli
* [x] download, showcase, pricing, login, view pages: setup triggering onclick events on buttons/links
* [x] test out again for all pages
* [x] deploy

## Analysis

What are advantages?

- a minimum script in the template => quicker loading time + no need to touch HTML
- more things to track + convenient to use with other products such as AdWords, double clicks etc. in the future if we decide to use them

To setup GTM, create an account at https://tagmanager.google.com then follow the instructions there.

Use debug mode provided by GTM to test out if everything is working. Use this Chrome extension for convenience https://chrome.google.com/webstore/detail/tag-assistant-by-google/kejbdjndbnbjgmefkgdddjlbokphdefk

**Comment by anuveyatsu** [comment]
FIXED and live in produciton

**Comment by zelima** [comment]
@anuveyatsu maybe a small tutorial of what changed and how we see/filter stuff would be useful for the team?

**Comment by anuveyatsu** [comment]
@zelima there are lots of different tutorials about using google tag manager so I wouldn't create our own one. I will leave a note in the frontend repo's README that we're now using Google Tag Manager.
