### ISSUE TITLE
[data-cli] documentation for users.

### ISSUE THREAD

**Issue by AcckiyGerman** [datahq/pm#140]
As a datahub user I want to read about `data-cli` generally and how to use it, so I can decide why I need this tool.

## Acceptance criteria

We have full documentation for `data-cli` everywhere:
- [x] Overview
- [x] All commands described

* Places:
    - [ ] github README.md
    - [ ] npmjs.com description
    - [ ] http://datahub.io/docs/features/data-cli (now it is outdated)

## Tasks

- [x] Update documentation
    - [x] Intro and Overview
    - [x] Describe all commands (use Help files)
- [x] review from ~~@zelima and @rufuspollock (this is our key product)~~ @akariv & @anuveyatsu 
- [x] Publish docs

**Comment by AcckiyGerman** [comment]
FIXED:
All data-cli documents are updated:
- github readme (npm readme updates automatically)
- http://datahub.io/docs/features/data-cli
