### ISSUE TITLE
CLI installable for Windows OS

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#143]
As reported in https://github.com/datahq/datahub-qa/issues/196 we want to offer to cli users an installable for Windows. The hypothesis is that it will ease installation process and more users will be able to set it up.

## Acceptance criteria

* [x] I can download MSI for Windows (x64 or x86) from https://datahub.io/download

## Tasks

* [x] create MSIs for v0.9.0 of the CLI
* [x] test out on different machines
* [x] upload it into v0.9.0 release in CLI releases
* [x] put it on the frontend

**Comment by anuveyatsu** [comment]
FIXED - https://datahub.io/download
