### ISSUE TITLE
[Epic] Premium data offer

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#144]
## Tasks

* [x] frontend - https://github.com/datahq/frontend/issues/261
* [x] funnel - https://github.com/datahq/datahub-kpis/issues/8
* [x] SEO
  * [x] Add meta-tags
  * [x] Sitemap
    * [x] generated dynamically (but not on request)
  * [x] Work on the top 10 datasets, add keywords and multiple wordings - make sure their ranks go up on various search queries

### Meta tags

This is partially implemented before - https://github.com/datahq/frontend/issues/254

Leftover:

* [x] "description" meta tag is static - make it dynamic

Review the current stage in 3 aspects:

* appearance in search results
* appearance when sharing on twitter
* appearance when sharing on facebook
* appearance when sharing other social media and messaging apps, e.g., test on gitter and slack

### Sitemap

NPM packages for generating sitemaps:

* **[winner]** https://www.npmjs.com/package/sitemap - stars: 418, weekly downloads: 39,199, last version: 10 months ago, last commit: 8 days ago
* https://www.npmjs.com/package/express-sitemap - stars: 53, weekly downloads: 1,211, last version: 10 months ago, last commit: 3m ago

Consider if we want to include all existing pages into sitemap (eg, dataset pages of individual users) or we want to include only special users' public datasets:

* `core`
* `machine-learning`
* `examples`

~~Create a script that re-generates sitemap after each commit and updates (?)~~
Sitemap is available at `/sitemap.xml` path.

Upload the sitemap to google search console - https://search.google.com/search-console - we only need to show URL for the sitemap and it'll be fetched periodically.

### SEO for the top 10 datasets: add keywords and multiple wordings

Current keywords:

```html
<meta name="keywords" content="data,datasets,data publishing,data sharing,data hosting,data package,reference data,indicators">
```

which is hardcoded so doesn't work as good as it could. We want to have dynamic keywords, e.g., on GDP dataset page, the keywords would be: "gdp,gross domestic product,country gdp,regional gdp,world gdp,data,datasets,data package".

Another method would be to try to search, e.g., `gdp data` and analyse top 3 results keywords etc.

**Comment by anuveyatsu** [comment]
This is how Twitter card for a dataset URL looks like:

<img width="450" alt="screen shot 2018-05-04 at 17 45 23" src="https://user-images.githubusercontent.com/17809581/39626254-fd659d94-4fc2-11e8-9cfb-66993ce749b0.png">

**Comment by anuveyatsu** [comment]
Sitemap is available at `/sitemap.xml` path and was submitted to google search console. It includes 125 pages.

**Comment by zelima** [comment]
@anuveyatsu anything remaining on this?

**Comment by anuveyatsu** [comment]
Closing as FIXED. We will need to verify what was the impact on rankings in search engines on the sprint review.
