### ISSUE TITLE
[Epic] "Deploy" funnel

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#146]
## Tasks

* [ ] Add missing events (based on issues in akariv/datahub-kpis)
  * [ ] Push -> Need to know if first push  - https://github.com/datahq/datahub-kpis/issues/1
  * [ ] Push successful event - https://github.com/datahq/datahub-kpis/issues/2
  * [ ] Visits in the showcase -> need to know if coming from cli - https://github.com/datahq/datahub-kpis/issues/3
  * [ ] Combine with npm stats - https://github.com/datahq/datahub-kpis/issues/4
* [x] Fork repo to datahq
* [ ] Automate run of script - https://github.com/datahq/datahub-kpis/issues/5
* [ ] Fetch historic data - https://github.com/datahq/datahub-kpis/issues/7
* [ ] Create a dataset from historical data - https://github.com/datahq/datahub-kpis/issues/7
