### ISSUE TITLE
[Epic] boot up newsletter system 

### ISSUE THREAD

**Issue by zelima** [datahq/pm#148]
As an Admin I want to boot up a newsletter system, so that my users can receive news about datahub updates.

## Acceptance Criteria 

* [ ] All users (except unsubscribed) are receiving updates (of their choice?) about Datahub and it's products (Eg new core dataset)

## Tasks

* [x] Design the newsletter template (@tanvir)
  * [x] Implement template in MailChimp (@tanvir)
  * [x] 'Sign up for newsletter' button on hompage, blog (@tanvir + @zelima)
  * [x] Write content for first newsletter (e.g. report on Q1) @rufus ?
* [ ] Process for adding new signups to the newsletter list
  * [x] Export user list from DB
  * [x] Import list to mailchimp
* [x]  Test it works
* [x]  Make sure unsubscribe works

## Analysis 

TODO #

**Comment by zelima** [comment]
FIXED - we have a template of the newsletter with contacts migrated from production database
