### ISSUE TITLE
JS SDK blog post and tutorial improvements

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#153]
Last improvements for JS SDK tutorial - https://datahub.io/docs/tutorials/js-sdk-tutorial
and blog post about it.

## Acceptance criteria

* [x] the tutorial is simplified
* [x] a blog post at `/blog/...`

## Tasks

* [x] review the tutorial
* [x] improve language and simplify it, e.g., make it shorter with assumptions that users don't need an overview and other off-topic things - they want to deploy data
* [x] write a blog post draft
* [x] get it reviewed
* [x] publish

**Comment by anuveyatsu** [comment]
FIXED - https://datahub.io/blog/javascript-sdk-for-data-deployment
