### ISSUE TITLE
Work with JSL re jointly curation of datasets

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#155]
## Tasks

* [x] create a team in 'datasets' org that is for JSL+Datopian
  * [x] add Ali to that team
* [x] create new repos for datasets from JSL
  * [x] Annual Consumer Price Index Percent Change 1974-2016
  * [x] Diagnosed Diabetes Prevalence 2004-2013
  * [ ] ~~Real Estate Across The United States Building Inventory~~
  * [x] US Race and Ethnicity Codes
* [x] identify and add datasets that will be jointly maintained
  * [x] NASA Temperature Anomalies By Latitude Bands Time Series
  * [x] gdp-uk 
  * [x] ICC-Incoterms
  * [x] nasdaq-listings
  * [x] natural-gas-prices 
  * [x] population-city
  * [x] ppp
  * [x] top-level-domain-names

**Comment by anuveyatsu** [comment]
FIXED - next steps would be:
- to transfer new core datasets from JSL to "datasets" org => publish under "core" user on datahub (with automation via Travis)
- start jointly-maintenance of selected datasets
