### ISSUE TITLE
Monitor and analyze SEO improvements

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#157]
## Acceptance criteria

* [x] we know how the latest implementations have affected traffic

## Tasks

* [x] Monitor impact of previous implementations, e.g., how meta tags and keywords affected top 10 datasets traffic
* [x] Analysis by end of the sprint (for next sprint planning)

**Comment by anuveyatsu** [comment]
FIXED and included in the hackmd (sprint plan and analysis)
