### ISSUE TITLE
Analyze optimize (experiments) data

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#158]
As we have setup A/B tests for Download page conversion on 9 May 2018, we want to analyse results and decide on which actions should be taken.

## Acceptance criteria

* [ ] we have outcomes from the experiments
* [ ] we have defined next actions

## Tasks

* [ ] by the end of the sprint analyse the reports
* [ ] come up with decisions and next steps
