### ISSUE TITLE
[Epic] Complete automated deploy on kubernetes

### ISSUE THREAD

**Issue by zelima** [datahq/pm#159]
Migrated on GCE Kubernetes we still need to automate redeploy of certain services.

## Acceptance Criteria

* [x] service is redeployed whenever change is made to auth repo
* [x] appropriate services are redeployed whenever dependent libraries are update (Eg specstore is updated when changes are made to plans, assembler, events etc..)
* [x] able to change secrets with simple script

## Tasks

* [x] Work for Auth image updated ~ 4h https://github.com/datahq/auth/issues/28
  * [x] Plan (Thursday morning) ~1h
* [x] appropriate images updated when dependant libraries are updated 4h - https://github.com/datahq/pm/issues/160
* [x] Script for auto creation of secrets ~4h - https://github.com/datahq/deploy/issues/59
* [x] Script for travis to create PR on production 3 https://github.com/datahq/deploy/issues/60

**Comment by zelima** [comment]
FIXED

**Comment by zelima** [comment]
While service images getting updated, one more thing is missing to complete this see https://github.com/datahq/deploy/issues/134

**Comment by zelima** [comment]
FIXED the remaining one as well
