### ISSUE TITLE
Preview large datasets

### ISSUE THREAD

**Issue by zelima** [datahq/pm#16]
As a Publisher I want to upload a 50Mb CSV so that the showcase page works - it does not crash by browser (because it is trying to load and display 50Mb of CSV)

## Acceptance criteria 

* [x] We have preview version of all resources and my browser does not crash

## Tasks

* [x] Backend: https://github.com/datahq/assembler/issues/16
  * [x] Generate the preview view
  * [x] Generate resources for views (maybe just preview views for now)
* [x] Frontend
  * [x] ~~frontend https://github.com/datahq/frontend/issues/89~~
  * [x] dpr-js https://github.com/datahq/frontend-showcase-js/issues/168

## Analysis 

Concepts:

- Primary views
- Preview views

### finance-vix example

Initial datackage.json:

```javascript
"resources": [
    {
      "name": "vix-daily",
      "path": "data/vix-daily.csv",
      "format": "csv",
      "mediatype": "text/csv",
      "schema": {
        "fields": [
          {
            "name": "Date",
            "type": "date",
            "description": "",
            "format": "any"
          },
          {
            "name": "VIXOpen",
            "type": "number",
            "description": ""
          },
          {
            "name": "VIXHigh",
            "type": "number",
            "description": ""
          },
          {
            "name": "VIXLow",
            "type": "number",
            "description": ""
          },
          {
            "name": "VIXClose",
            "type": "number",
            "description": ""
          }
        ],
        "primaryKey": "Date"
      }
    }
  ],
  "views": [
    {
      "name": "graph",
      "title": "VIX - CBOE Volatility Index",
      "specType": "simple",
      "spec": {
        "type": "line",
        "group": "Date",
        "series": [
          "VIXClose"
        ]
      }
    }
  ]
```

After pipelines:

```javascript
{
  "resources": [
    {
      "name": "vix-daily",
      "path": "data/vix-daily.csv",
      "format": "csv",
      "mediatype": "text/csv",
      "schema": {...}
    },
    {}, // derived csv
    {}, // derived json
    { // even though json data we have a table schema
      "name": "...",
      "path": "data/preview/vix-daily.json",
      "datahub": {
        "derivedFrom": [
          "vix-daily"
        ],
        "forView": [
          "..."
        ],
        "type": "derived/preview" // data will be json ...
      }
    }
  ],
  "views": [
    {
      "name": "graph",
      "title": "VIX - CBOE Volatility Index",
      "specType": "simple",
      "spec": {
        "type": "line",
        "group": "Date",
        "series": [
          "VIXClose"
        ]
      }
    },
    {
      name: 'datahub-preview-{resource-name}',
      specType: 'table',
      datahub: {
        type: 'preview'
      },
      transform: {
        limit: 100000
      },
      resource: [
        'vix-daily.csv'
      ]
    }
  ]
}
```

**Comment by anuveyatsu** [comment]
FIXED - now we generate preview views + `derived/preview` version of resources. They then are used in frontend to render tables with previews.
