### ISSUE TITLE
Service images are updated when dependent libraries are updated

### ISSUE THREAD

**Issue by zelima** [datahq/pm#160]
As a developer I want to have services updated whenever I change the codebase of the dependent libraries. Eg I made changes to assembler --> specstore service needs to be redeployed

## Acceptance Criteria

- [x] Changes are live whenever I make changes

## Tasks

- [x] See instructions https://docs.travis-ci.com/user/triggering-builds/
  - [x] Add another commmand in apps_travis_script ('trigger')
    - [x] Sends trigger to specific repo with custom commit message ('rebuild because x updated with commit y')
  - [x] Each travis build will trigger the necessary services based on context
- [x] wait till travis-ci.org migrates to travis-ci.com (see analysis below)
- [x] List the repos
  - [x] auth -> datahub-auth, specstore, bitstore
  - [x] planner -> specstore
  - [x] assembler -> specstore
  - [x] events -> specstore 
  - [x] datahub-emails -> auth
- [x] Update `.travis.yml`
  - [x] update envs vis token

## Analysis

Investigating a bit in how Travis build triggering, it seems like it the feature of the Travis pro (paid) account  - as shown in instructions you should log in with `travis login --pro` and request token with `travis token --pro` commands. While travis-ci.com says that it's Always free for open source projects, not sure whether we should set up the billing and assign to one the plans anyway. 

Anyway, I tried to integrate Datahq apps on travis.com without filling billing information and got following: Some of the repos got integrated but for most of them (once that are already integrated to travi-ci.org) cannot be migrated to travis-ci.com at this time because they are currently active on their legacy platform travis-ci.org. This feature will be available shortly. Meanwhile I'm getting following error from https://github.com/datahq/auth

```
{
  "@type": "error",
  "error_type": "repository_inactive",
  "error_message": "cannot create requests on an inactive repository",
  "repository": {
    "@type": "repository",
    "@href": "/repo/4814846",
    "@representation": "minimal",
    "id": 4814846,
    "name": "auth",
    "slug": "datahq/auth"
  }
}
```

Reading their [docs](https://docs.travis-ci.com/user/open-source-on-travis-ci-com/#Existing-Open-Source-Repositories-on-travis-ci.org) thei will start migrating everything to travis-ci.com by the end of the Q2 2018 and think we can use their features without paing anything. So I reccomend waitting for now on automating this part of the auto-deploy and manually trigger bulds.

> On May 2nd, 2018 Travis CI announced that open source projects will be joining private projects on travis-ci.com!

> New open source user accounts and repositories will be able to use travis-ci.com right away, while existing user accounts and repositories will be migrated over time.

> ### Existing Open Source Repositories on travis-ci.org #
>
> Open source projects and their build history will continue to run on travis-ci.org for now.
>
>However, open source repositories will be migrated to travis-ci.com gradually, beginning at the end of Q2 2018. You will receive an email when the migration for a repository is complete. This is an opt-in process: to have a repository migrated over, it must first be activated on travis-ci.com.
>
>Currently, open source repositories that were private in any time in their history may be added to travis-ci.com. The option to migrate to travis-ci.com for active open source repositories that were always open source will come soon.
>
>Repositories may also be migrated without their build history or build settings (including environment variables) immediately. Please contact support support@travis-ci.com and include “Repository Migration” somewhere in the subject line, and the name of the repository in your email.

**Comment by zelima** [comment]
Moving to backlog for now (see analysis)

**Comment by zelima** [comment]
FIXED
