### ISSUE TITLE
Debug anomalies with the metrics

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#161]
As discussed during the sprint plan, the number of users who ran `data login` is lower than the number of new users who pushed at least 1 dataset (within given 2 weeks period). Assuming that a user must run `login` command to be able to publish a dataset, the number of users who ran `login` command cannot be lower.

## Acceptance criteria

* [x] we identified the reason of that anomaly
* [x] the metrics are tracked correctly

## Tasks

* [x] check who is those 6 new users who published any datasets - it might be that some of them a new developers who setup `datahub=dev` environment variable so we're not tracking their usage

**Comment by anuveyatsu** [comment]
FIXED

We need to replace this event:
`category: cli, action: login`

with this event:
`category: login, action: client, label: login-cli`
