### ISSUE TITLE
Blog post re revamped awesome pages

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#168]
As the DataHub team, we want to announce our work on awesome pages so our Users aware of changes and can benefit from it.

## Acceptance criteria

* [x] a blog post about new awesome pages at `/blog/...`

## Tasks

* [x] create a structure
* [x] draft
* [x] get a reviews
* [x] improve per reviews
* [x] publish
* [x] deploy
* [x] announce on the chat and twitter

**Comment by anuveyatsu** [comment]
FIXED - https://datahub.io/blog/revamped-awesome-collections-data-sets-that-are-grouped-by-subject and https://twitter.com/datahubio/status/1006141376155791361
