### ISSUE TITLE
[Epic] SEO - 18 June 2018

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#169]
## Tasks

* [x] Improve CTR - https://github.com/datahq/pm/issues/171
* [x] More focus on the awesome pages + blog posts (see analysis below)
* [x] Use graph images as "meta image" tags on datasets pages
  * we can use a graph image as “meta image” tag so it appears in the search results, which must be super cool and unique, therefore, should recieve a lot more clicks
* [x] More domains linking to our website - https://github.com/datahq/pm/issues/170

### More focus on the awesome pages + blog posts

Hypothesis: visitors search for “economic data” and clicks on a post or awesome page about “economic data”. They spend 1-2 minutes to read the article and finds number of links to our datasets pages (e.g., s-and-p, gdp and so on - we have a lot). Visitors are happy and their session duration is more than average + they've found everything they need in the one place which is Datahub!

What we can do:

* [x] add missing pages into the sitemap, e.g., blog posts
* [x] research on “sublinks” in the search results - we want to have them!
* awesome pages - will be done in a separate issue
  * once logos are created use them as "meta image" tag
  * create "economic data" awesome pages - this is already in the another issue
* [x] blog
  * [x] ~~use the first image in the blog post as a “meta image” tag~~ use 'image' attr of frontmatter as 'meta image' tag

**Comment by anuveyatsu** [comment]
FIXED
