### ISSUE TITLE
More domains linking to our website

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#170]
As the DataHub team, we want to have many different websites with the links to DataHub so we attract more traffic + we improve average positioning of our website in the search results.

Right now we posting on twitter only (and GitHub obviously) and we used to do it on Reddit. But we want to have as many as possible websites that have links to DataHub (we also have links from Frictionlessdata, OKFN ...)

## Acceptance criteria

* [x] we've posted our article(s) on at least 10 websites/platforms
  * [x] it has lots of links to datahub

## Tasks

* [x] create a list of websites where we can post our blog posts
* [x] identify an appropriate blog post or tutorial to be posted on other websites
* [x] post them first on Facebook/Twitter
* [x] consider canonical tags when duplicating content: https://www.quora.com/Should-I-publish-the-same-blog-in-different-platforms
* [x] post a copy of the selected articles in the list of websites/platforms that was chosen in the first task

**Comment by anuveyatsu** [comment]
FIXED:
- medium: https://medium.com/@datahub
- posting now on regular basis on Reddit and http://news.ycombinator.com/
- posting on gist
- posting on facebook along with twitter
- answering relevant questions with the links to datahub on reddit, quora and stackexchange
