### ISSUE TITLE
Improve Click Through Rate

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#171]
As the DataHub team, we want to increase the average CTR so we receive more traffic from the organic search.

Currently, our average CTR is 3.3% in the last 3 months.

*Don’t touch pages that have a rank of 1 or 2 (they’re already super great, e.g., country-list dataset).*

## Acceptance criteria

* [ ] implementations from the tasks are deployed
* [ ] we're monitoring the search console by the end of the sprint

## Tasks

* [ ] see what keywords are using companies in the adwords ads (for relevant queries) which then we can target (create a new issue if there is interesting findings)
* [ ] analyse keywords in search console, e.g., see where we’re having lots of impressions but low CTR due to positioning. Include those keywords in the content (description/title etc.)
* [ ] use common keywords that are proved to be effective
