### ISSUE TITLE
Conduct an analysis to determine which datasets to collect

### ISSUE THREAD

**Issue by Branko-Dj** [datahq/pm#174]
Analysis for 500 datasets project. Our goal is to determine which datasets should be prioritized for extraction. Also to automate the approach so we can collect stats in the future

## Tasks
- [x] Take a look at the data requests for info about most requested data
- [x] Create questions for user survey so we get feedback from our users
- [x] Create an additional field for data request where the user will enter the category of dataset he/she is requesting for future stats gathering

## Acceptance criteria
- [x] The list of categories and/or names for datasets to be collected is assembled for the current period
- [x] We have an automated approach for collecting stats about datasets that are requested

**Comment by Branko-Dj** [comment]
#FIXED. Analysis written in sprint plan document
