### ISSUE TITLE
Datasets extraction from UNECE

### ISSUE THREAD

**Issue by Branko-Dj** [datahq/pm#176]
As part of collecting 500 datasets I want to compile a list of interesting datasets and extract them from UNECE (United Nations Economic Commission for Europe) [website](http://w3.unece.org/PXWeb/en).

## Tasks
- [x] Create a list of interesting datasets to be extracted
- [x] Elaborate and categorize these datasets
- [x] Extract them on a local machine
- [x] Publish on datahub

## Acceptance criteria
- [x] Datasets are listed and their details documented
- [x] Datasets are published on DataHub

**Comment by Branko-Dj** [comment]
FIXED - datasets can be found at https://datahub.io/unece
