### ISSUE TITLE
[Epic] Tracking and Optimization

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#177]
## Tasks

* [x] structured data and rich results [1.5d] - https://github.com/datahq/frontend/issues/301
* [x] Sitelinks (or sublinks) [0.5d]
  * https://github.com/datahq/frontend/issues/297
  * check awesome pages if we can implement something similar
* [x] work on next top 10 datasets [1d] - https://github.com/datahq/frontend/issues/302
* [x] Showcase page interactions [1d] - https://github.com/datahq/frontend/issues/295
* [x] track events on server-side - https://github.com/datahq/frontend/issues/300

**Comment by anuveyatsu** [comment]
FIXED
