### ISSUE TITLE
Promote awesome pages/datasets

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#178]
## Acceptance criteria

* [x] new awesome pages are shared on various forums and as blog posts

## Tasks

* [x] Prepare publication checklist (what needs to be done when publishing a blog post or sharing a post + templates)
* [x] keep posting/promoting awesome pages and datasets on forums/blogging platforms/social networks
      * [x] Reference Data
      * [ ] Climate Change Data
      * [x]  Demographics (population)
      * [x] Stock Market Data

**Comment by anuveyatsu** [comment]
Publication checklist (for more details go to analysis hackmd):

* gitter channels: "datahubio" and "frictionlessdata"
* reddit - share with short sentance linking to datahub
* medium - publish entire thing with notice that it was originally posted on datahub
* http://news.ycombinator.com/ - share just like on reddit
* twitter - share with call-to-action message, link and some hashtags: #opendata #datasets ...
* facebook - like twitter

**Comment by anuveyatsu** [comment]
FIXED
