### ISSUE TITLE
Track and show space usage

### ISSUE THREAD

**Issue by zelima** [datahq/pm#18]
As an Admin I want to see how usage is being used by which users so that I can prevent over-use and charge for it one day

As a Publisher I want to know the total space I'm using (and perhaps breakdown by dataset) so that I know what this will cost

As a Consumer I want to know the total size of what i'm about to download so that I know how long it will take etc

## Acceptance criteria

* [x] we know number of resources as well as total size of resources
* [x] displayed in frontend 

## Tasks

* [x] Add up the total: use the MetaStore API: search will return aggregate info not just count of the results but also statistics info ... - @zelima  https://github.com/datahq/metastore/issues/14
    ```
    {
      "results": [],
      "summary": {
        "total": 3
        "totalBytes": .....  
      }
    }
    ```
  * [x] update README  https://github.com/datahq/metastore/issues/14
* [x] Display in the dashboard incorporate this info - also show them total number of datasets etc  (frontend)  https://github.com/datahq/frontend/issues/88

**Comment by rufuspollock** [comment]
@zelima as a small comment i think the long analysis is part of the metastore issue and does not belong here: datahq/metastore#14 -i'd also (mostly) reserve analysis for the initial analysis and use comments to report problems you encountered so that people can follow the updates and flow and re-reading the issue later is easier to understand.

**Comment by zelima** [comment]
FIXED. Analysis moved back to datahq/metastore#14
