### ISSUE TITLE
Datasets automated operations

### ISSUE THREAD

**Issue by Branko-Dj** [datahq/pm#184]
I want to be able to automate operating on a group of datasets. Operations such as packaging csv files, modifying metadata, pushing datasets for different users, validating etc. should be automated. Also modifying datasets to add category tags is a nice feature to have.

## Tasks

- [x] Create a module with two classes - **Dataset** and **DatasetGroup**
- [x] Class **Dataset** should be made of the following variables and methods: 
    - [x] variables that describe given dataset such as name, source, localFilePath, categoryTags etc.
    - [x] methods that allow packaging, validating, pushing, obtaining data and metadata

## Acceptance criteria

- [x] The module can be used to: 
    - [x] package a dataset and a group of datasets
    - [x] push dataset and a group of datasets by using different users
    - [x] modify json packages

**Comment by Branko-Dj** [comment]
FIXED - the module can be found at https://github.com/Branko-Dj/dataset-operations
