### ISSUE TITLE
Analysis of data related forums

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#187]
As the Datahub team, we want to know what is popular in the data forums/communities so we know which direction we should take.

## Acceptance criteria

* [x] we identified what should we do, e.g., which subjects to cover, what datasets to scrape etc.

## Tasks

* [x] analyse reddit
  * [x] identify relevant subreddits
  * [x] analyse all time top posts
  * [x] identify what could be popular to have on datahub
* [x] analyse opendata stackexchange
  * [x] analyse popular tags
  * [x] list tags/subjects/datasets we can have on datahub
* [x] analyse crossvalidated stackexchange
  * [x] analyse popular tags
  * [x] list tags/subjects/datasets we can have on datahub
* [x] analyse quora
  * [x] try to search for popular data related questions

**Comment by anuveyatsu** [comment]
FIXED and discussed with @akariv (see hackmd for more details)
