### ISSUE TITLE
Blog post for ARFF data format

### ISSUE THREAD

**Issue by Branko-Dj** [datahq/pm#188]
As a Data Wrangler / Data Scientist, I come across many obscure formats such as ARFF and want to google them so i understand what they are for and whether i can use them

Task: create a short tutorial for ARFF format that is reusable as a blog post. Make sure it mentions (tabular) data packages and DataHub at the end and explain why you'd want to useit and any tools for converting to it.

## Tasks
- [ ] Explanation of the format with good links
- [ ] Link to relevant tools
- [ ] Conversion to / from data packages
- [ ] Examples on DataHub that might be relevant
