### ISSUE TITLE
Blog post for Parquet data format

### ISSUE THREAD

**Issue by Branko-Dj** [datahq/pm#189]
As a Data Wrangler / Data Scientist, I come across many obscure formats which I want to google so I can understand what they are for and whether I can use them

Task: create a short tutorial for Parquet format that is reusable as a blog post. Make sure it mentions (tabular) data packages and DataHub at the end and explain why you'd want to use it and any tools for converting to it.

## Tasks
- [ ] Explanation of the format with good links
- [ ] Link to relevant tools
- [ ] Conversion to / from data packages
- [ ] Examples on DataHub that might be relevant

**Comment by Branko-Dj** [comment]
Yes, still active. I will be working on it

**Comment by zelima** [comment]
@Branko-Dj what do you mean by "I will be working on it"? In current milestone or generally? if in this milestone please add to it
