### ISSUE TITLE
Support Excel

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#19]
As a Publisher I want to push my Excel file to the DataHub so that I have it stored, get a CSV version and a nice showcase page.

* Want to be able download original Excel
  * Also want to be able download CSV and JSON versions of each sheet
* Preview for the file
  * Preview for each sheet of Excel file

Present situation: you couldn't push Excel at all (see https://github.com/datahq/datahub-cli/issues/161) and even when we fixed basic problem we don't handle Excel as tabular properly in backend (or CLI?) so no CSV or JSON generated, and showcase does not work (in what way?)

## Acceptance criteria

* [x] I can push Excel files to DataHub using CLI
* [x] There are previews and downloads for CSV/JSON versions for each sheet in the Excel file

## Tasks

* [x] Make Excel files to be treated as tabular resources - https://github.com/datahq/datahub-cli/issues/161
* [x] Have option to select a sheet by passing sheet index - https://github.com/datahq/datahub-cli/issues/162
* [x] Work on push command to auto include only one sheet's schema in Excel resource - https://github.com/datahq/datahub-cli/issues/177
* [x] Refactor push command to include schemas for all sheets - https://github.com/datahq/datahub-cli/issues/166
* [x] Rework download files table - https://github.com/datahq/frontend/issues/90
* [x] Docs - https://github.com/datahq/frontend/issues/86
* [x] Refactoring re tutorial - https://github.com/datahq/datahub-cli/issues/185

## Analysis

> Q from anu: Main question is do we process all sheets or should we prompt user to select one sheet?

```mermaid
graph LR

excel --> csv1[Sheet 1 - CSV]
excel --> csv2[Sheet 2 - CSV]
csv1 --> csv1p["Sheet 1 - Preview (JSON)"]
```

How datapackage.json would look like when pushing Excel file?

Refer to https://github.com/frictionlessdata/tabulator-py#xlsxlsx but how would it work if I want to specify multiple sheets?

```yaml
processing:
 - # Processing steps that need to be done on sources to get proper data streams
   input: <source-resource-name - e.g. `my-excel-resource`>
   output: <destination-resource-name - e.g. `my-excel-resource-sheet-1`>
   tabulator: # Currently we're only supporting tabulator transformations
     # These are sample options for tabulator, see its docs for all available options
     headers: 2 
     sheet: 1
   schema: # Overwrite schema for resource
     fields:
       - name: bla
         type: string
       # table schema
```

**Comment by anuveyatsu** [comment]
This epic is blocked because pushed Excel files sheets are not being processed as expected in the backend (pipelines). 

/cc @akariv @rufuspollock 

https://datahub.io/anuveyatsu/sample-2sheets-great-impala-86

**Comment by anuveyatsu** [comment]
FIXED - see example dataset for excel - https://datahub.io/anuveyatsu/excel-lucky-monkey-72

Also, you can see tutorial re pushing Excel here - http://datahub.io/docs/getting-started/push-excel
