### ISSUE TITLE
Engage with survey respondents

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#190]
As the Datahub team, we want to engage our survey respondents so we can learn more about what they want. 

## Acceptance criteria

* [x] we have emailed all of our respondents for new survey
* [x] the sent emails are personalized, eg, have respondents name, mention their answers

## Tasks

* [x] review answers of the new survey
* [x] collect email addresses and add them into freshdesk contacts
* [x] send personalized emails mentioning features they would pay for and suggesting setup a call or discuss it in details
* [x] suggest to join the gitter chat

**Comment by anuveyatsu** [comment]
FIXED. Emails are sent via freshdesk.
