### ISSUE TITLE
Share datasets on social network

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#192]
As the DataHub team, we want to share our important/popular datasets on social network so people can visit our website to explore it and bring traffic.

## Acceptance criteria

* [x] increased traffic for selected datasets from domains where we've posted

## Tasks

* [x] select 10 the most popular and interesting (eg with graphs) datasets
  * [x] post 1 dataset per weekday
* [x] ask datahub dev team to choose their favourite dataset and share it via their social networks accounts
* [ ] analyze traffic by the end of the sprint

## Analysis

While we want to share popular datasets, we also want to select those that have nice visualization so it is interesting to view.

Top 10 datasets with graphs:

* [x] https://datahub.io/core/s-and-p-500
* [x] https://datahub.io/core/global-temp
* [x] http://datahub.io/core/gold-prices
* [x] https://datahub.io/core/bond-yields-uk-10y
* [x] https://datahub.io/core/pharmaceutical-drug-spending
* [x] https://datahub.io/core/co2-ppm
* [x] https://datahub.io/core/house-prices-us
* [x] https://datahub.io/core/bond-yields-us-10y
* [x] https://datahub.io/core/oil-prices
* [x] https://datahub.io/core/sea-level-rise

**Comment by anuveyatsu** [comment]
FIXED. Traffic analysis will be done with review of biweekly stats.
