### ISSUE TITLE
Analyse Google analytics and prepare report to draw conclusions

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/pm#193]
Do an analysis of datahub.io with the information from Google Analytics. Study and document the changes that have been observed in user's behaviour since the datahub homepage re-design.

## User Stories
* As Product Owner, I want an analysis of Google Analytics data from last 6 months, so that i can draw conculsions of the impact of the new design on the users.
* As Tanvir, I want to analyze changes in user's behaviour in new design, so that i can figure out ways to improve engagement
* As a Teammember, I want to analyze changes in user's behaviour in new design, so that i can understand the constant drop in CLI downloads

## Acceptance Criteria
* [x] A report providing concrete evidence of user's behavior changes since the redesign
* [x] Meeting with concerned team members to draw conclusions
* [x] Formulate the necessary steps to be taken to improve on the current user behavior on the website to increase engagement

## Tasks
* [x] Analyse Google Analytics data of last months
* [x] Draw reports comparing the user's behavior before and after the home redesign
* [x] Inspect the usage patterns
* [x] Make the report available for the team
* [ ] Hold a presentation to know team's thoughts

**Comment by tanvirchahal** [comment]
## Key Stats

### Avg time on page

* Avg time spent on page is up by 350%, Avg time spent turned to 00:01:31 as compared to 00:00:20 in april

### Next page navigation summary

* /search visits up by 129% 
* /pricing visits up by 344%
* /login visits up by 212% 
* /blog visits up by 323%
* /core down by -46%
* /downloads down by -20%
* /requests down by -57%

Conclusion would be that users are using navbar links since they don't have main call-to-action buttons that redirect to ceratin pages. E.g., in the old design the most visited pages were `/core`, `/download`  and `/requests` and you can see that those pages have significant descrease in visits. As a results we have decreased number of CLI downloads and data requests.

### Bounce rate

* bounce rate increased from 14% to 47% 

(Note: Looks like a steep escalation in bounce rate, but when compared to Jan,Feb,March, the bounce rate change from about 42%-43% to 47% in June. Were there speciafic changes made in April?)

Definition of Bounce Rate: the percentage of visitors to a particular website who navigate away from the site after viewing only one page.

Hight Bounce rate could be a by-product of increased avg time spent? 350% increase in avg time means it's getting the right information for users right on their visit.

## Things Learnt

* New design has been able to enge the user for a considerably longer time. This could mean that the data tables and data-sets on homepage are engaging users, could also mean that it answers the questions of users without visiting a further pages.
* Lack of proper call to actions to key offers like /core /requests /downloads has lead to a drop in users reaching the pages.
* The high bounce rate could be a reason because of ambigious landing hero section.  It looks pretty but is it practical?
* Too many links, some of them are scroll links. Total 24 links on new homepage (excluding)

## Tanvir's Remarks

* Should move the offer sections above the fold
* Clear call to actions boost traffic on right pages
* Reduce the number of unnecessary links
* Avoid scroll to section links.

## Actions

* Should move the offer sections above the fold
* Reduce the number of unnecessary links
* add a link to `/download` page in the 'Publish' section of homepage
* add a prominent button/link to `/download` that says, eg, `Get our data wrangler tool`
