### ISSUE TITLE
Docs about organization accounts

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#195]
As a User, I'm interested in having org account so my team can have a collection of datasets in our account.

## Acceptance criteria

* [x] there is a form that I can fill in and request an org account creation
* [x] there is a description of how it is done
* [x] there is an admin section about how to create an org account

## Tasks

* [x] create a google form to collect all necessary information for org accounts
* [x] create docs page where we have:
  * [x] a small introduction about org accounts and why it's needed
  * [x] explain current situation, eg, we can do it manually now
  * [x] place the form so people who's interested can leave their details
* [x] deploy
* [x] create instructions for the team so anybody can complete org account creation process

**Comment by anuveyatsu** [comment]
FIXED. Admin section about how to do it is in internal docs repo.

https://datahub.io/docs/features/teams-and-permissions
