### ISSUE TITLE
Tutorial about how to use multiple Datahub accounts

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#196]
As a User, I want to know how do I manage multiple accounts on DataHub so that I can publish/work with my datasets from several accounts, eg, personal one and org one.

## Acceptance criteria

* [x] written tutorial about how to use multiple accounts in the tutorials section of docs page

## Tasks

* [x] create the structure of the article
* [x] draft the tutorial
* [ ] get a review from eg Branko
* [ ] improve
* [x] publish

**Comment by anuveyatsu** [comment]
FIXED - https://datahub.io/docs/tutorials/how-to-use-multiple-datahub-accounts
