### ISSUE TITLE
Check core packages (and push)

### ISSUE THREAD

**Issue by Mikanebu** [datahq/pm#2]
We want to have a list of core data packages with status in the gist.  

## Acceptance criteria

* [x] We have a script for doing this
* [x] We have a list of data packages with status

Output CSV (like current status spreadsheet but something we can auto update):

```
| pkg name | github url  |  run-date | validation-status | validation-message | publish-status 

```

## Tasks

Do all of this by hand for say 5 packages to start with:

* [x] Clone all packages to directory X - do by hand
* [x] Run the validate program for each data package (update the status.csv)
   *  input is a list of directories to data packages core-list.txt + base path to directory X and generate
* [x] Run normalize program if validate has an errors - update status.csv
  * [x] Push correction to datasets repo ...
  * [x] Re-run validate

Bonus / later:

* [x] Publish a couple by hand to check it works
* [x] Script to *clone* all packages into a directory
* [x] Script to *push* all valid packages (use new CLI lib)

## Analysis

```
for each core package:
  output of data validate on datapackage.json (against latest version of the specs - TODO: check this)
  # valid
  if valid:
    run data check
  if not valid:
    report ...
    data norm:
      if error: report
      else:
        Check the diff - is there any diff. If not error (since norm made no difference)
        if diff: suggest the do data norm by hand (i think not worth trying to automate this)
```

**Comment by Mikanebu** [comment]
Status of Core Data Packages:  https://gist.github.com/Mikanebu/5e57c1218e9f6946d3f3fde160f1f020
Script for generation list of dp status
https://gist.github.com/Mikanebu/1f8e6a802ae1042f8730336452c51f0f

Still need to finish normalize

**Comment by zelima** [comment]
@Mikanebu can you add estimate?

**Comment by Mikanebu** [comment]
Script to clone, check  and push core data packages is located in the following repository: https://github.com/datahq/core-datasets-tools

**Comment by Mikanebu** [comment]
FIXED
