### ISSUE TITLE
[awesome] page for bibliographic data plus a blog post

### ISSUE THREAD

**Issue by rufuspollock** [datahq/pm#204]
As someone interested in [open/free] bibliographic data I want to know what datasets are available so that I can get them

TODO: maybe split out blog post as separate task

## Acceptance criteria

* [ ] Awesome page at `/awesome/biblio` 
  * Academic metadata, bibliographic metadata, bibliographic data
* [ ] Blog post about availability of (open) bibliographic data

## Tasks

* [ ] Awesome page - see https://github.com/datahq/awesome-data/issues/29
* [ ] Blog post: "Where can you find [good] bibliographic metadata [in bulk]?"
  * [ ] Second post: "Where can I find [good] bibliographic metadata APIs?"
