### ISSUE TITLE
Publish open-ml datasets

### ISSUE THREAD

**Issue by Branko-Dj** [datahq/pm#206]
As a datahub We have 200 open-ml datasets that we wish to publish under the user machine-learning

## Acceptance criteria
- [x] On a machine-learning user page there should be additonal 100 datasets from open-ml

## Tasks
- [x] By using repo [dataset-operations](https://github.com/Branko-Dj/dataset-operations) initialize and validate datapackages. 
- [x] Publish datasets with new datapackages

**Comment by Branko-Dj** [comment]
FIXED! Open-ml datasets can be found under our machine-learning user https://datahub.io/machine-learning
