### ISSUE TITLE
Share climate change dashboard on social platforms

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#207]
As the Datahub team, we want to share our work on Climate Change Dashboard so that interested people can find it, visit it and enjoy it.

## Acceptance criteria

* [ ] the page is shared on sites according to checklist

## Tasks

* [ ] share the dashboard on `dataisbeautiful, datasets, opendata` subreddits
* [ ] share on other social platforms (refer to our checklist)
  * [ ] gitter chats
  * [ ] https://news.ycombinator.com/
  * [ ] twitter
  * [ ] facebook
  * [ ] medium ?
