### ISSUE TITLE
Improve world bank awesome page

### ISSUE THREAD

**Issue by Branko-Dj** [datahq/pm#208]
We wish to update the world-bank [awesome page](https://datahub.io/awesome/world-bank) with current status

## Acceptance criteria
- [x] The new page is created that contains important details about our current world-bank datasets

## Tasks
- [x] Add a list of interesting datasets to the page
- [x] Update it with general info about them

**Comment by Branko-Dj** [comment]
FIXED - new information is added to https://datahub.io/awesome/world-bank
