### ISSUE TITLE
[Analytics] Identify the current situation/improvements re showcase page traffic

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#209]
As the DataHub team, we want to know how are our users on showcase page are interacting so that we know if our improvements are having any impact.

As the DataHub team, we want to know how traffic on showcase page is changing so that we know if we can take actions if needed or know that we're doing things correctly.

## Acceptance criteria

* [ ] traffic for showcase pages for last 3 months is identified
* [ ] interactions on showcase pages for last 3 months are identified

## Tasks

* [x] go to GA dashboard and analyse the traffic
* [ ] write down results

**Comment by anuveyatsu** [comment]
## Interactions on the showcase page

% of interacting users (clicking on any `a` links on the page) out of total incoming users:

![newplot](https://user-images.githubusercontent.com/17809581/42771752-0b887b24-894a-11e8-98d5-e85a74d12fc3.png)

We can tell that the number of interactions has significantly increased.

## Traffic on showcase pages

Our traffic on core datasets pages is decreasing compared to previous periods:

<img width="988" alt="screen shot 2018-07-16 at 22 53 08" src="https://user-images.githubusercontent.com/17809581/42772211-978a0f10-894b-11e8-8fd4-56b8230d1a61.png">

By investigating the source, we can tell that we have a drop in direct visits to our site:

<img width="1000" alt="screen shot 2018-07-16 at 23 01 00" src="https://user-images.githubusercontent.com/17809581/42772423-342ecbda-894c-11e8-929e-05163d8ff04e.png">

while visits from Organic Search remains roughly the same:

<img width="994" alt="screen shot 2018-07-16 at 23 00 33" src="https://user-images.githubusercontent.com/17809581/42772442-44dc7e96-894c-11e8-9970-489a078e9488.png">

**Comment by anuveyatsu** [comment]
FIXED - see the writings above
