### ISSUE TITLE
Cryptocurrency datasets

### ISSUE THREAD

**Issue by Branko-Dj** [datahq/pm#210]
In an effort to add new and interesting datasets we wish to publish some datasets concerning cryptocurrencies (trends, prices etc.)

## Acceptance criteria
- [x] We have new and interesting datasets published under a new user - **cryptocurrencies**

## Tasks
- [x] Create a new user - cryptocurrencies
- [x] Scrape new and interesting datasets for this topic
- [x] Publish them

**Comment by Branko-Dj** [comment]
FIXED - datasets can be found at datahub.io/cryptocurrency
