### ISSUE TITLE
S&P 500 companies data for the last 10 years from SEC

### ISSUE THREAD

**Issue by Branko-Dj** [datahq/pm#211]
S&P 500 companies is one of our most popular datasets. We wish to enhance it by adding data going back 10 years.

## Acceptance criteria
- [x] We have a new dataset with balance sheets and income statements for the last 10 years from SEC

## Tasks
- [x] Find CIKs for S&P companies
- [x] Based on CIKs scrape SEC for balance sheets and income statements
- [x] Package and publish the dataset

**Comment by Branko-Dj** [comment]
CLOSED
