### ISSUE TITLE
data push url

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#22]
As a Publisher I want to be able to push an online file so that it is stored and showcased (and regularly re imported)

**Current situation:** if I push a remote file, it would fail saying:

```
ENOENT: no such file or directory
```

> What about pushing a remote datapackage? `data push  https://example.com/mydataset/datapackage.json`
>
> ANS: not that important (a rare case)

## Acceptance criteria

* [x] I can push a file at a url to datahub
* [x] I can setup how regularly it should be re-imported

## Tasks

* [x] Research the source spec (and check backend will support what is needed)
  * [x] Research whether infer schema can work with a stream and limited stream (e.g. only look at first 10k rows)
  * [x] Do we need to download the file first (?) - we hope not ...
* [x] setup schedule (crontab) - https://github.com/datahq/datahub-cli/issues/168
* [x] refactor data.js addSchema method to pass stream to infer - https://github.com/datahq/data.js/issues/17
* [x] refactor cli's `data-push.js` to handle URLs - https://github.com/datahq/datahub-cli/issues/189

## Analysis

```yaml=
meta:
  owner: <owner username>
  ownerid: <owner unique id>
  dataset: <dataset name>
  version: 1
  findability: <published/unlisted/private>
inputs:
  -
    kind: datapackage
    url: <datapackage-url>
    tabulator:
      k: v
schedule:
   - crontab: "0,15,30,45 H/4 sunday * *" # documented somewhere (celery beat)
```

To generate one we will need to read (download) the file. It would look like:

```
{
  name: 'myfile',
  format: 'csv',
  path: 'url',
  schema: {...} // ?
}
```

E.g., for `https://raw.githubusercontent.com/datasets/co2-ppm/master/data/co2-annmean-gl.csv`:

```
{
  name: 'co2-annmean-gl`,
  format: 'csv',
  path: 'https://raw.githubusercontent.com/datasets/co2-ppm/master/data/co2-annmean-gl.csv',
  schema: {...}
}
```

**Comment by anuveyatsu** [comment]
FIXED - see two identical datasets:

- pushed as local file - https://datahub.io/anuveyatsu/sample-cowardly-dog-6
- pushed as remote file - http://datahub.io/anuveyatsu/sample-strong-stingray-63
