### ISSUE TITLE
World cities with >25k population with their provinces and countries

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#223]
As a User, I want to have a CSV data that contains world cities with >25k population so that I can use it in my research.

## Acceptance criteria

* [x] I have CSV data for cities with >25k population with their provinces/regions and countries

## Tasks

* [x] analyse data source for what we can and should do to gather the data
* [x] create a script that processes the data and generates CSV data

**Comment by anuveyatsu** [comment]
FIXED - the data is in gitlab repo
