### ISSUE TITLE
List of universities around the World

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#227]
As a User, I want to have a CSV data with list of world universities so that I can use it in my research.

## Acceptance criteria

* [x] I have a CSV data with university name, full location (city, region, country), Web address, email address

## Tasks

* [x] research and analyse available data
* [x] analyse how we can obtain email addresses - e.g., some algorithm based on domains..
* [x] generate the data

**Comment by anuveyatsu** [comment]
FIXED. The repo is on gitlab.
