### ISSUE TITLE
Get country and language name data in local script from CLDR

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#229]
As a User, I want to have local country and language name in the local script so that I can use it for my business purposes.

## Acceptance criteria

* [x] For each row in the locales data I have a country and language name in the local script

## Tasks

* [x] analyse data from CLDR - structure etc.
* [x] create a python script to fetch that data and put into CSV

**Comment by anuveyatsu** [comment]
FIXED see our internal docs
