### ISSUE TITLE
misc issue from user feedback on 12.09.2017

### ISSUE THREAD

**Issue by Mikanebu** [datahq/pm#23]
## Tasks

* [x] Simpler way to get started and test it is working - https://github.com/datahq/frontend/issues/94
* [x] `info command`: encountered a poor error message - https://github.com/datahq/datahub-cli/issues/172
* [x] help message - https://github.com/datahq/datahub-cli/issues/171
  * [x] data push help message is not clear and short
  * [x] data normalize - poor CLI documentation at basic help screen (need more info - normalizes data package against spec 1.0)

## Analysis

* [ ]  Simpler way to get started and test it is working
  * ACTION: add `data info {some dataset on datahub}` to getting started
  * As Brook I want to run a simple non-side-effects command to see everything is working before I do something bigger so that I don’t damage anything and feel more certain …
    * I don’t want to write to my disk straight away … (where will it get written!)
    * data info https://datahub.io/core/finance-vix
* [ ] `info command`: encountered a poor error message => an issue
https://gist.github.com/brew/eb47b4a6a3df01caa25b38079de47444
: should be no data package found …
* [ ] data push help message is not clear and short => an issue
  * add real example, providing path and explain path options 
* [ ] data normalize - poor CLI documentation at basic help screen (need more info - normalizes data package against spec 1.0)
  * `data normalize` help message is good, with `Usage, Option, Examples` sections

**Comment by rufuspollock** [comment]
FIXED.
