### ISSUE TITLE
Create many-to-many relationship in the regional datasets

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#230]
As a User, I want to have many to many relationships for the appropriate tables so that I can easily manage my data in the future.

## Acceptance criteria

* [x] these have many-to-many relationship:
  * [x] countries to currencies

## Tasks

* [x] normalize currencies data
* [x] create raw currencies data without reference to countries
* [x] create `country_to_currency` data that is a many-to-many relationship
* [x] update `datapackage.json`
* [x] update SQL tables
* [x] create SQL scripts to setup relationships between tables in the DB

**Comment by anuveyatsu** [comment]
FIXED - see on gitlab
