### ISSUE TITLE
Currency symbol data

### ISSUE THREAD

**Issue by Branko-Dj** [datahq/pm#231]
Fix missing currencies and add multiple versions of symbols for currencies in regional data

## Acceptance criteria
- [x] The file `currency.csv` is modified to satisfy current wishes

## Tasks
- [x] Find comprehensive sources of information about currency names, alphabetic symbols and sign symbols
    - source used: https://github.com/tammoippen/iso4217parse
- [x] Add missing values to `currency.csv` in the appropriate gitlab repository
