### ISSUE TITLE
Dialing prefix data

### ISSUE THREAD

**Issue by Branko-Dj** [datahq/pm#232]
Find values for IDD prefixes that are missing from our current sources
Some missing values can be found at
http://www.idd.com.au/international-dialling-codes.php

## Acceptance criteria
- [x] Fill up the missing values for prefixes in `dial.csv`

## Tasks
- [x] Find a source for dialing information that has some of missing values
    - [x] Current source used PhoneNumberMetadata.xml from https://github.com/googlei18n/libphonenumber
- [x] Do some research in order to find missing IDD prefixes for countries with these alpha 2 iso codes: ['AQ', 'BV', 'GS', 'HM', 'PN', 'TF', 'UM']
    - [x] AQ (Antarctica) From what I was able to find it seems that some of their stations are in a category of australian external territories which have **IDD = 00** http://www.dialingnumber.com/city_australiaexternal.htm, but there are other countries with their claims on Antarctic territory. In the absence of information, I leave it blank.
    - [x] BV (Bouvet Island) - it is uninhabited. Couldn't find any info about IDD
    - [x] GS (South Georgia and the South Sandwich Islands) - South Sandwich Islands are uninhabited, South Georgia Island doesn't seem to have phones installed https://wikitravel.org/en/South_Georgia_Island. But then again [here](http://www.idd.com.au/international-dialling-codes.php) it says that the **IDD = 00**
    - [x] HM (Heard Island and McDonald Islands) - also uninhabited. As an Australian external territory, it seems that **IDD = 00**
    - [x] PN (Pitcairn Islands) - **IDD = 00** https://en.wikipedia.org/wiki/Telephone_numbers_in_the_Pitcairn_Islands
    - [x] TF - French Southern Territories - According to [timeanddate website](https://www.timeanddate.com/worldclock/dialingcodes.html?p1=397&p2=281&number=353633) **IDD = 00**
    - [x] UM - United States Minor Outlying Islands - According to [timeanddate website](https://www.timeanddate.com/worldclock/dialingcodes.html?p1=3399&p2=281&number=353633) **IDD = 011**

**Comment by Branko-Dj** [comment]
FIXED!
