### ISSUE TITLE
Territory subdivisions for countries from cldr

### ISSUE THREAD

**Issue by Branko-Dj** [datahq/pm#233]
Scrape territory subdivisions from unicode http://unicode.org/cldr/charts/28/supplemental/territory_subdivisions.html

## Acceptance criteria
- [x] Data is scraped from the page, converted into a csv format and uploaded to gitlab

## Tasks
- [x] Scrape data from unicode
- [x] Upload script and csv file to gitlab

**Comment by Branko-Dj** [comment]
FIXED
