### ISSUE TITLE
Add "related datasets" for the top 10 datasets

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#234]
As a Datahub team, we want to promote similar datasets on our popular showcase pages so that users can find exactly what they're looking for.

## Acceptance criteria

* [x] our most popular showcase pages have 'Similar datasets' section with the links to related showcase pages

## Tasks

* [x] identify 10 most popular showcase pages
* [x] identify related datasets for these showcase pages
* [x] modify descriptor files by adding 'related' property
* [x] re-push to datahub

## Analysis

Selected showcase pages and related datasets:

* s-and-p-500-companies
  * s-and-p-500
  * s-and-p-500-companies-financials
  * finance-vix
  * nyse-other-listings
* language-codes
  * country-list
  * country-codes
  * continent-codes
  * un-locode
* s-and-p-500
  * s-and-p-500-companies
  * s-and-p-500-companies-financials
  * finance-vix
  * nyse-other-listings
* world-cities
  * country-list
  * country-codes
  * population
  * continent-codes
* continent-codes
  * country-list
  * language-codes
  * airport-codes
* global-temp
  * co2-ppm
  * co2-fossil-by-nation
  * sea-level-rise
  * glacier-mass-balance
* un-locode
  * country-list
  * country-codes
  * airport-codes
  * language-codes
* country-codes
  * country-list
  * language-codes
  * airport-codes
  * continent-codes
* gold-prices
  * oil-prices
  * natural-gas

**Comment by anuveyatsu** [comment]
FIXED see showcase pages for selected datasets
