### ISSUE TITLE
Publish more sports (football) datasets

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#236]
As the DataHub, we want to publish more sports data so that people interested in sports can find datasets on our site.

We've seen good traffic for ATP data that was published under `sports-data` publisher + we've seen huge traffic re football data during the WC + we've received a data request for football data and done some research that can be used as a starting point for this. All these are the motivation behind this issue.

## Acceptance criteria

* [x] major Europe leagues' data are published under `sports-data` user: EPL, Seria A, La Liga, Bundesliga

## Tasks

* [x] identify the best source for fetching data
* [x] package and publish
* [x] add to sitemap

**Comment by anuveyatsu** [comment]
FIXED see https://datahub.io/sports-data
