### ISSUE TITLE
Actions on JSL partnership (July-August)

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#237]
New items from our last meeting on 18 July 2018.

## Acceptance criteria

* [ ] automatic publishing is set up for 11 jointly maintained repositories

## Tasks

* [ ] Set up Travis build to push to datahub for all jointly maintained repositories
* [ ] Check why README is not using a description from dp.json on JSL datasets (also check meta description property)
* [ ] Check if it’s ok to have JSL website link on `/JohnSnowLabs` page
