### ISSUE TITLE
Improve documentation for Markdown

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#238]
See for more details https://github.com/datahq/datahub-qa/issues/159

## Acceptance criteria

* [x] markdown docs covers all datahub specific features

## Tasks

* [x] read and analyse what is missing in the current version of the docs
* [x] add missing points, especially, datahub specific features

**Comment by anuveyatsu** [comment]
FIXED see updated https://datahub.io/docs/misc/markdown
