### ISSUE TITLE
Blog post for sports data on datahub

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#239]
As a User who's interested in sports, I want to know if new sports datasets are published so that I can have a look/download it.

As a Datahub team, we want to promote newly published sports datasets so that we attract more traffic to the website.

## Acceptance criteria

* [x] blog post about sports data at `/blog`

## Tasks

* [x] create a structure of the post
* [x] write a draft
* [x] get a review from Esteban
* [x] improve per review
* [x] publish and deploy

**Comment by anuveyatsu** [comment]
FIXED - https://datahub.io/blog/sports-data-on-datahub
