### ISSUE TITLE
Core datasets maintenance

### ISSUE THREAD

**Issue by Branko-Dj** [datahq/pm#240]
## Acceptance criteria
* [ ] core datasets in https://github.com/datasets/registry/blob/master/core-list.csv are all checked to be up to date and their scraping scripts are working properly

## Tasks
* [ ] go through each `core` dataset and check if scraping scripts are working
* [ ] check if it is not outdated
* [ ] cross check with the registry -

**Comment by zelima** [comment]
@Branko-Dj any work is done on this? If no think we can remove estimate and close DUPLICATE of #258

**Comment by Branko-Dj** [comment]
@zelima Why not just add it to the epic?

**Comment by zelima** [comment]
@Branko-Dj please remove estimate if no work has been done on this
