### ISSUE TITLE
S&P 500 financial data 

### ISSUE THREAD

**Issue by Branko-Dj** [datahq/pm#248]
We wish to scrape multiple datasets from SEC and then to normalize and unpivot them so nice graphs can be made

## Acceptance criteria
* [ ] Data is unpivoted and normalized and we have 10 datasets from S&P 500

## Tasks
* [ ] scrape all data for ~10 popular companies
* [ ] unpivot/normalize data
* [ ] add more metadata, e.g., descriptions/field data types
* [ ] publish it under new user called `s-and-p-500-financial-data`
* [ ] add link to https://datahub.io/awesome/stock-market-data so that people can explore more
