### ISSUE TITLE
Football data

### ISSUE THREAD

**Issue by Branko-Dj** [datahq/pm#249]
We have a data request for various football related data: scores, corners etc.

## Acceptance criteria
* [ ] Football data is ready with as much info as we can find

## Tasks
* [ ] Research sources for data requested
* [ ] setup work
* [ ] regular update (weekly)
* [ ] analysis are in a specified document which needs some updates in terms of requested fields

**Comment by zelima** [comment]
Is this duplicate of https://github.com/datahq/awesome-data/issues/1? If so please close with appropriate label
