### ISSUE TITLE
Research electron apps

### ISSUE THREAD

**Issue by rufuspollock** [datahq/pm#26]
As a Publisher I want to install a tool to publish my datasets quickly and easily and with auto-updating so that I am able to publish easily and be effortlessly up to date with the tools

* This could be installing the CLi
* Could be a desktop app

## Acceptance criteria

* [x] How hard would it be to do an MVP datahub app that:
  * [x] You can install (on different platforms
  * [x] Shows a welcome screen
  * [x] Installs the command line
  * [ ] ~~(Future) Runs in the background~~
* [x] Easy to build cross-platform

## Tasks

**We will focus on electron based on our preliminary investigations and the fact it can reuse existing JS tooling**

Part I

* [x] Research existing builders (focus on building for mac, then linux - windows a bonus)
* [x] Skeleton a basic electron app
* [x] Build a package

Part II

*  [x] Simple home page
   * [x] logo
   * [x] We are installing / updating the CLI
   * [x] You can read the tutorial here while we are doing this: ...
* [x] Auto-install the CLI (and update if installed)
* [x] Report completion and suggest they take it for a spin: instructions for how to do that ...
* [x] Build (mac, linux)

Part III

* [ ] Auto-updating for the electron app itself
* [ ] Build again

Future (not this task)

* [ ] Drag and drop files or folders to upload ...

**Comment by rufuspollock** [comment]
https://www.electron.build/ -- looks the best 3.4k stars

https://github.com/electron-userland/electron-packager - useful but mainly reused in other higher level builders e.g. https://github.com/electron-userland/electron-forge

https://electron.atom.io/docs/tutorial/application-distribution/

**Comment by anuveyatsu** [comment]
**UPDATES:**

* Auto update for app itself (part 3) would take ~2h
* We also need to think about how we going to publish the app, e.g., via GitHub releases (using Travis)
* Haven't done testing on running background

**Comment by anuveyatsu** [comment]
FIXED:

* repo for the desktop app - https://github.com/datahq/data-desktop
* published application for macOs and linux - https://github.com/datahq/data-desktop/releases/tag/v0.1.0
