### ISSUE TITLE
Improve KPIs tracking with focus on Premium Data offer

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#260]
As an Admin, I want to see nice and clear funnel for Premium Data offer with all related KPIs so that I can see what we should improve to better sell our product/service.

Our current KPIs dataset is focused on deploy funnel, however, we have decided to make it secondary offering and make premium data offer as the main product. See http://datahub.io/datahq/datahub-kpis

## Tasks

* [x] brainstorm/analyse what should we track to make the funnel accurate and informative - 
* [x] funnel should include all pages where we have premium data offering - 
* [x] track figures found in the prev task -

**Comment by anuveyatsu** [comment]
FIXED see issues in this epic for details.
