### ISSUE TITLE
Brainstorm/analyse what we need to track re premium data funnel

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#261]
As an Admin, I want to see nice and clear funnel for Premium Data offer with all related KPIs so that I can see what we should improve to better sell our product/service.

## Acceptance criteria

* [x] I have a list of figures that we will track for our premium data funnel

## Tasks

* [x] brainstorm what we should track
* [x] analyse which pages should be involved
* [x] discuss with Esteban and create a final list

**Comment by anuveyatsu** [comment]
1. Overall site visitors aka users.
2. Visitors of the pages where we promote premium data offer: showcase pages, search page, collections page, dashboard page, pricing page.
3. Clicks on the offer.
4. Form submissions.

**Comment by anuveyatsu** [comment]
FIXED
