### ISSUE TITLE
Re-implement KPIs dataset with a focus on premium data

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#263]
As an Admin, I want to see nice and clear funnel for Premium Data offer with all related KPIs so that I can see what we should improve to better sell our product/service.

## Acceptance criteria

* [x] this dataset http://datahub.io/datahq/datahub-kpis is re-designed so that it shows me improved premium data funnel
* [x] it updates automatically on a daily basis
* [x] it has graphs that demonstrate trends in premium data offer

## Tasks

* [x] analysis
* [x] re-write scripts
* [x] update resources
* [x] add views

**Comment by anuveyatsu** [comment]
FIXED, see https://datahub.io/datahq/datahub-kpis
