### ISSUE TITLE
Check/implement tracking for all new links/buttons added recently

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#266]
As an Admin, I want to track all new implementations such as links and buttons so that I have an understanding of what works well.

## Acceptance criteria

* [x] I can see custom report(s) in the GA dashboard for new links/buttons

## Tasks

* [x] check implementations added in September and October
* [x] put trackers for the links/buttons and other elements where applicable
* [x] create custom reports in GA dashboard

**Comment by anuveyatsu** [comment]
FIXED see GA dashboard => Customization => Saved reports
