### ISSUE TITLE
Track what people are searching on Find Data page

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#268]
As an Admin, I want to know what our users are searching on Find Data page so that I understand what kind of data they're looking for.

## Acceptance criteria

* [ ] I have a custom report in the GA dashboard to see what users search

## Tasks

* [ ] analysis of how we're tracking key words/phrases on the Find Data page
* [ ] create a custom report in the GA
