### ISSUE TITLE
An email sending feature in case of dataflow's failure

### ISSUE THREAD

**Issue by zelima** [datahq/pm#270]
As a publisher, I want to be notified by Email if the processing of dataflows failed for some reason so that I am aware and I can fix

## Acceptance Criteria

* [ ] Getting the email with small descriptions of what went wrong.

## Tasks

* [ ] Do an analysis
* [ ] Define failures
* [ ] Come up with implementation plan

**Comment by zelima** [comment]
DUPLICATE of #284
