### ISSUE TITLE
dpp v2 (based off dataflows processors)

### ISSUE THREAD

**Issue by zelima** [datahq/pm#274]
As Datahub, we want to release dpp v2 that uses dataflows as processors, so that we can start writing external scrapers/flows/processors and publishing data so

## tasks

* [ ] Migrate processors to use dataflows
* [ ] Wrapper for flows as processors
* [ ] Fix stdout issues (allow printing from flows / processors)
* [ ] Write blogpost introducing the changes and showing some examples
