### ISSUE TITLE
Analysis on automation of core datasets quality/update checks

### ISSUE THREAD

**Issue by Branko-Dj** [datahq/pm#276]
This is related to one of our Q4 initiatives: “Implement an exception report to know when datasets have errors or are of sub-standard quality.

## Acceptance criteria
- [ ] We have a detailed list of all core datasets along with info about their quality

## Tasks
- [ ] Create a google sheet with various columns detailing different info about quality for core datasets
- [ ] Go through each core dataset and check its quality

**Comment by Branko-Dj** [comment]
FIXED! Spreadsheet can be found at https://docs.google.com/spreadsheets/d/14JPXVE2YSu_AmFvKqWzpPdDUuqYP8CdvV_BciB0ddJg/edit#gid=0
