### ISSUE TITLE
Create blog post re data usage

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#28]
We want to create a blog post about space usage statistics in the dashboard:

<img width="491" alt="screen shot 2017-09-22 at 19 30 22" src="https://user-images.githubusercontent.com/17809581/30746732-96c6aef8-9fcc-11e7-8e58-9a61f7042a73.png">

## Tasks

* [x] create a layout (plan) for the article in hackmd
* [x] write short paragraph about the feature
* [x] request a review (+proof reading)

**Comment by anuveyatsu** [comment]
FIXED and published - http://datahub.io/blog/space-usage
