### ISSUE TITLE
Track premium funnel KPIs per page

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#280]
As an Admin, I want to track premium data funnel KPIs per page so that I can assess the performance of each page with premium data offer and compare approaches.

## Acceptance criteria

* [x] on http://datahub.io/datahq/datahub-kpis page I can see graphs for KPIs per page

## Tasks

* [x] check/analyse what is missing to create views and put a tracker if needed
* [x] create views using KPIs per page

**Comment by anuveyatsu** [comment]
FIXED, see the third graph on  http://datahub.io/datahq/datahub-kpis
