### ISSUE TITLE
Set up system to measure the cost of acquiring and managing datasets

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#281]
As an Admin, I want to know how much it takes to acquire and manage a dataset so that I can plan better in our sprint planning/analysis sessions.

As a Data Wrangler, I want to have a guide of how I'd measure cost of dataset acquiring so that I can tell my colleagues how much would take me to do a certain task.

## Acceptance criteria

* [ ] I have a system (eg, step-by-step guide) of how to measure how much time/money I've spent on a particular task (dataset aqcuiring/managing)

## Tasks

* [ ] conduct analysis to identify what are key figures (eg, hours, $)
* [ ] analyse recent dataset acquiring processes (eg, ask Branko and Irakli)
* [ ] set up a measurement system
