### ISSUE TITLE
Track what searches people are making to land on our site

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#283]
As an Admin, I want to know what queries people are using to land on our site so that:

* I can understand how accurate are our wordings
* I can align our website to attract a more accurate/related audience

## Acceptance criteria

* [ ] set of keywords and key phrases with the relative number of clicks/appearances etc.

## Tasks

* [ ] read https://www.entrepreneur.com/article/276722
* [ ] analyse google's search console
* [ ] create a spreadsheet with the results
