### ISSUE TITLE
[Epic] Multiple user on dpp server

### ISSUE THREAD

**Issue by zelima** [datahq/pm#285]
As a Datahub (or Publisher), I want to run dataflows (on schedule), with multiple different users, so that I can publish them for other users than core

## Acceptance Criteria

* [x] able to publish https://github.com/datasets/football-datasets under sports-data user
  * [x] No travis is involved in automation

## Tasks

* [x] refactor datapackage-pipeline-datahub to accept config file name https://github.com/datahq/datapackage-pipelines-datahub/issues/8
  * [x] accept various option for push https://github.com/datahq/datapackage-pipelines-datahub/issues/9
* [x] update factory to keep multiple config files https://github.com/datahq/factory/issues/2

**Comment by zelima** [comment]
FIXED https://datahub.io/sports-data/spanish-la-liga
