### ISSUE TITLE
[Epic] Improvements for status page

### ISSUE THREAD

**Issue by zelima** [datahq/pm#289]
At the moment we have a very basic status page per owner. We would like to use more of it's features like groping components, automatically updatable statuses etc...

## Acceptance Criteria

* [ ] Status reports per dataset
* [ ] Auto updates on resolve

## Tasks

* [ ] Read docs of statuspage and do analysis  
* [ ] group components 
* [ ] auto updates on fix
