### ISSUE TITLE
Blog section on datahub.io

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#33]
We want to create a blog section, where we can post our news, announce new features and more.

Path to blog: `/blog/`
Path to a blog post: `/blog/{slug}/`

Blog section can be a list of posts - one per row. See examples from https://github.com/blog and https://zeit.co/blog

Each blog post can be quite simple - similar to zeit or github would be nice. Overall page layout can be similar to our docs pages - http://datahub.io/docs/getting-started/pushing-data

## Acceptance criteria

* [x] I can see a blog post in file blog/my-title-slug.md with title {title} and date yyyy-mm-dd at https:/datahub.io/blog/my-title-slug
  * [x] Show the date of the post and (if possible) author
  * [x] Commenting: At bottom of each post "If you have questions, comments or feedback join our chat channel or open an issue on our [tracker][link to qa ...]"
  * [x] Note this is also good on documentation posts ...
* [x] I can see blog section at https://datahub.io/blog with posts listed in reverse date order
  * [x] Show dates of post
 
## Tasks

* [x] blog post re space usage - https://github.com/datahq/pm/issues/28 - put this up first so we have something to trial with ...
* [x] Write a very simple test for blog page and index page (?)
* [x] Implement /blog/{post-page} - https://github.com/datahq/frontend/issues/110
* [x] implement `/blog/` index page - https://github.com/datahq/frontend/issues/108 

## Analysis

All blog posts should have `.md` extension and placed in `/blog/` directory. So we can iterate through all documents in that directory and create a list of posts

Each blog post looks like:

```
---
title: My post
date: 2017-10-03
slug: my-post
author: anu # this is your username
---
```

GET /blog/my-post-2017-09-11

=>

```javascript=
router.get(['blog', 'blog/*'], showBlog)

function showBlog(req, res) {
  // get req.params
  // use to open a file from /blog/
  // if does not exist -> 404
  // 
}
```

{
  "anu": {
    gravatar: 
    fullname: ...
  }
}

For parsing frontmatter - https://github.com/dworthen/js-yaml-front-matter

**Comment by anuveyatsu** [comment]
FIXED - see http://datahub.io/blog
