### ISSUE TITLE
Blog post about the changes took a place in spec v1

### ISSUE THREAD

**Issue by Mikanebu** [datahq/pm#34]
We want to have a blog post about spec v1 changes, so users get an understanding why we made it and why it is important, plus have a section for normalization script, so users know how it handles changes in the new spec v1

## Acceptance criteria 

* [x] Blog post about spec v1 
* [x] Section for  normalization

## Tasks 

* [x] Write blog post about spec v1 changes 
* [x] Add section about normalization, how it handles changes in the spec v1

**Comment by Mikanebu** [comment]
FIXED, blog post is live now on http://datahub.io/blog/upgrade-to-data-package-specs-v1
