### ISSUE TITLE
Blog posts for 23 Oct 2017 sprint

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#36]
## Tasks

* [x] Blog post about the changes took a place in spec v1 - https://github.com/datahq/pm/issues/34
* [x] blog post about pushing excel files - https://github.com/datahq/pm/issues/41
* [x] blog post about previews in showcase page - https://github.com/datahq/pm/issues/38
* [x] blog post about zip versions - https://github.com/datahq/pm/issues/39

**Comment by anuveyatsu** [comment]
FIXED
