### ISSUE TITLE
Frontend quality

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#37]
The frontend quality related issues.

## Tasks

* [x] update instructions in showcase page - https://github.com/datahq/frontend/issues/115
* [x] hover on graphs shows day of month etc - https://github.com/frictionlessdata/datapackage-render-js/issues/40
* [x] Frontend should not hang/fail when assembler (or other services) are down - https://github.com/datahq/frontend/issues/91
* [x] refactor rendering of `licenses` property in the summary table - only expect the property to be an array of objects and render all available licenses one by one - https://github.com/datahq/frontend/issues/112

Secondary

* [x] Misc items - https://github.com/datahq/frontend/issues/113
* [ ] no title for single files - https://github.com/datahq/frontend/issues/77
* [ ] Pipelines page improvements - https://github.com/datahq/frontend/issues/109
* [ ] Placeholder for previews in non-tabular files (xlsx, topojson, json) - https://github.com/datahq/frontend/issues/111
* [ ] titles per views (normal views) when there is no title - https://github.com/frictionlessdata/datapackage-render-js/issues/41

**Comment by anuveyatsu** [comment]
FIXED all main items. Secondary items are remaining in the icebox for now.
