### ISSUE TITLE
website functional testing

### ISSUE THREAD

**Issue by Mikanebu** [datahq/pm#42]
@Mikanebu commented on [Mon Oct 09 2017](https://github.com/datahq/frontend/issues/114)

As a developer I want to have whole system under test so that whenever I make new changes I am sure that nothing else is broken.

## Acceptance criteria 

* [x] Show case pages work ok: finance-vix or co2-ppm [more later] 
  * [x] Verify page loads - 200 OK and contains content you would expect
  * [x] Verify that pages load in a reasonable time (for now just record that time). Time to first byte, time to html loaded, time to all data loaded.
  * [x] Verify that download links work [works = 200]
  * [x] Verify that downloaded data makes sense [content is as expected, check zip files]
  * [x] Verify that views appear correctly [last of all as requires headless - maybe do headless to start with ...]
  * [x] Save outcome stats to a csv (so we have a history)

## Tasks 

* [x] read about chromless and puppeter and understand how they work
* [x] decide what aspects you need to test on the showcase page.
  * check showcase page returns 200 
  * dataset title is there 
  * page title is there 
  * README is there
    * has some content
  * table is there 
    * has some content
  * check resources are there
  * check all download links work fine(csv,json,zip)
    * check zip content
  * datapackage.json is there 
  * check views
    * hover over graph results with some points
* [x] write simple script and assert expected results (response is 200, titles, readme)
* [x] refactor to handle more complicated case(table, resources, downloads, dp.json)
* [x] tests graphs, hovers, etc.. 
* [x] page loading time
  * [x] find out how to track page loading time 
* [x] Output result in CSV

## Analysis

* How do we test stuff that involves JS?
  * Use headless chrome? e.g. see 
    * https://github.com/GoogleChrome/puppeteer, 
    * https://medium.com/@kensoh/chromeless-chrominator-chromy-navalia-lambdium-ghostjs-autogcd-ef34bcd26907
    * https://github.com/graphcool/chromeless

* decide on column names
  * `id` - timestamp
  * `name` - dataset name
  * `page_status` - status code and description
  * `page_title` - page title
  * `dataset_title` - dataset title
  * `readme` - contains readme: OK|NOT OK
  * `csv_links` - status code and description
  * `csv_preview_links` - status code and description
  * `json_links` - status code and description
  * `zip_links` - status code and description
  * `datapackage_json` - status code and description
  * `total_load_time` - total loading time
  * `script_laod_time` - script loading time
  * `layout_load_time` - layouts loading time
  * `tables` - contains table: OK|NOT OK
  * `graphs` - contains graphs: OK|NOT OK

**Comment by zelima** [comment]
@Mikanebu Is there anything left on this? if no - please close

**Comment by Mikanebu** [comment]
FIXED, script is located in https://github.com/datahq/frontend-functional-tests, issue to setup travis for running daily is here https://github.com/datahq/frontend-functional-tests/issues/3
