### ISSUE TITLE
Converts `%Y` to `%Y-%m-%d` with the current date. 

### ISSUE THREAD

**Issue by Mikanebu** [datahq/pm#46]
We want to update `date` property in datapackage.json where data in `%Y` format. 

## Acceptance criteria 

* [x] all core datasets that have `date` field  with data in the form of `%Y` type from `date` to `year`

## Tasks

* [x] identify core datasets for the `date` field
* [x] update `date` field in resources
* [x] republish

## Analysis 

When we assign type `date` to the column with the value in `%Y` format. It converts it into `%Y-%m-%d` using published `day` and `month`.  For example, `1991` will be converted to `1991-10-13`. It is probably related to `tabulator` library, how it handles this format. 
See:  http://datahub.io/core/cpi, https://datahub.io/core/co2-fossil-global, https://datahub.io/core/employment-us ...
I tested first with `employment-us` by changing `date` field type to`year` and `date` field column generated correctly.

List of datasets needs to update:
https://datahub.io/core/cash-surplus-deficit - DONE
http://datahub.io/core/cpi DONE
http://datahub.io/core/gdp DONE
http://datahub.io/core/inflation DONE
http://datahub.io/core/population DONE
http://datahub.io/core/ppp DONE

These following datasets have a problem with table view:
Reason: it errors 
```
"Wrong type for header: Year and value: 1751-10-18"
```
Somehow it uses old data, the current data value is `1751`

http://datahub.io/core/co2-fossil-global DONE
http://datahub.io/core/gdp-uk DONE
http://datahub.io/core/gini-index DONE 
https://datahub.io/core/glacier-mass-balance DONE
http://datahub.io/core/global-temp DONE

Resolved: It took time to update data

**Comment by Mikanebu** [comment]
FIXED, all date fields with the value `%Y` updated from `date` to `year`. Total datasets: 11.
