### ISSUE TITLE
Check core datasets for readme, remove sources section

### ISSUE THREAD

**Issue by Mikanebu** [datahq/pm#51]
We want to have all our core datasets to follow README writing convention
 
## Acceptance criteria

* [x] all core dataset's `README.md` is followed README writing convention according to the http://datahub.io/docs/data-packages/publish-faq#readme

## Tasks

* [x] check all core datasets for `README.md` and update if necessary
* [x] republish to DaaHub

## Analysis

README for the following datasets needs to be updated according to the http://datahub.io/docs/data-packages/publish-faq#readme: 

https://github.com/datasets/cash-surplus-deficit
https://github.com/datasets/co2-fossil-global
https://github.com/datasets/co2-ppm
https://github.com/datasets/continent-codes
https://github.com/datasets/corruption-perceptions-index
https://github.com/datasets/cpi
https://github.com/datasets/eu-emissions-trading-system
https://github.com/datasets/employment-us
https://github.com/datasets/gdp
https://github.com/datasets/gdp-uk
https://github.com/datasets/genome-sequencing-costs
https://github.com/datasets/gini-index
https://github.com/datasets/global-temp
https://github.com/datasets/global-temp-anomalies
https://github.com/datasets/house-prices-uk
https://github.com/datasets/ICC-Incoterms
https://github.com/datasets/IMO-IMDG-Codes
https://github.com/datasets/imf-weo
https://github.com/datasets/inflation
https://github.com/datasets/investor-flow-of-funds-us
https://github.com/datasets/iso-container-codes
https://github.com/datasets/media-types
https://github.com/datasets/membership-to-copyright-treaties
https://github.com/datasets/natural-gas-prices
https://github.com/datasets/population
https://github.com/datasets/ppp
https://github.com/datasets/s-and-p-500-companies
https://github.com/datasets/top-level-domain-names
https://github.com/datasets/uk-sic-2007-condensed
https://github.com/datasets/unece-package-codes

**Comment by Mikanebu** [comment]
FIXED, all the following core datasets are updated for `README.md`

**Comment by Mikanebu** [comment]
FIXED, all the following core datasets are updated for `README.md`
https://github.com/datasets/cash-surplus-deficit
https://github.com/datasets/co2-fossil-global
https://github.com/datasets/co2-ppm
https://github.com/datasets/continent-codes
https://github.com/datasets/corruption-perceptions-index
https://github.com/datasets/cpi
https://github.com/datasets/eu-emissions-trading-system
https://github.com/datasets/employment-us
https://github.com/datasets/gdp
https://github.com/datasets/gdp-uk
https://github.com/datasets/genome-sequencing-costs
https://github.com/datasets/gini-index
https://github.com/datasets/global-temp
https://github.com/datasets/global-temp-anomalies
https://github.com/datasets/house-prices-uk
https://github.com/datasets/ICC-Incoterms
https://github.com/datasets/IMO-IMDG-Codes
https://github.com/datasets/imf-weo
https://github.com/datasets/inflation
https://github.com/datasets/investor-flow-of-funds-us
https://github.com/datasets/iso-container-codes
https://github.com/datasets/media-types
https://github.com/datasets/membership-to-copyright-treaties
https://github.com/datasets/natural-gas-prices
https://github.com/datasets/population
https://github.com/datasets/ppp
https://github.com/datasets/s-and-p-500-companies
https://github.com/datasets/top-level-domain-names
https://github.com/datasets/uk-sic-2007-condensed
https://github.com/datasets/unece-package-codes
