### ISSUE TITLE
[docs] Getting data tutorial

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#52]
Write tutorial about how users can get data from DataHub using different programming languages and tools:

* "r" links
* cURL
* R
* Python
* Pandas
* JS
* SQL
* Ruby
* PHP

## Acceptance criteria

* [x] tutorial covers instructions as per points above
* [x] online tutorial at https://datahub.io/docs/getting-started/getting-data

## Tasks

* [x] write the tutorial
  * [x] introduction
  * [x] cover all points above
  * [x] summary
* [x] review
* [x] publish

**Comment by anuveyatsu** [comment]
FIXED, now available in testing webiste - https://testing.datahub.io/docs/getting-started/getting-data
