### ISSUE TITLE
[datasets] Create a graph for "population" dataset

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#53]
We want to have a graph in the "population" dataset with some useful visualization. E.g., we can have a trend for World population. We may also have a graph for comparison trend between China and India as they are the countries with the largest populations (3rd comes USA but with huge gap from 2nd place).

## Acceptance criteria

* [x] a graph for world population

## Tasks

* [x] workaround in the own account on datahub
  * [x] create a view in the datapackage.json using simple spec
* [x] publish under core

**Comment by anuveyatsu** [comment]
FIXED - will be live once pipelines are finished at https://datahub.io/core/population
