### ISSUE TITLE
Install DataDog (or equivalent) on prod servers

### ISSUE THREAD

**Issue by Mikanebu** [datahq/pm#55]
As a system administrator I want to setup DataDog on production servers, so we can see the metrics from our services.

## Acceptance criteria

* [x] DataDog is setup

## Tasks

* [x] Sign up with `datahub@datopian.com` for free(up to 5 hosts)
* [x] Get the Datadog Agent running
* [x] Add metrics into dashboard

**Comment by Mikanebu** [comment]
FIXED, datadog installed on testing environment
