### ISSUE TITLE
Write API Tests

### ISSUE THREAD

**Issue by Mikanebu** [datahq/pm#56]
@Mikanebu commented on [Mon Nov 06 2017](https://github.com/datahq/frontend/issues/128)

As a developer, I want to test all API endpoints, to be sure that all our serves works fine and returns a valid response. #

## Acceptance criteria

* [ ] All API endpoints are tested on `travis` 

## Tasks

* [x] decide what language to use (Python or javascript)
* [x] list out all the services with API endpoint
* [x] prepare request body

## Analysis

Example dataset to test: https://datahub.io/examples/test-data-package-for-api-test

#### Status

* /source/{identifier}/status DONE
* /source/{identifier}/info DONE

#### Upload

* /source/upload DONE
 
#### 

* /source/update DOES NOT WORK

#### Get authorized upload URL(s)

* /authorize

#### Get information regarding the datastore

* /info

#### Check an authentication token's validity

* /auth/check

#### Get permission for a service

* /auth/authorize

#### Change the username

* /auth/update

#### Receive authorization public key

* /auth/public-key

#### Search

* /metastore/search
* /metastore/search/events

#### Resolves username to userid

* /resolver/resolve
 

---

@rufuspollock commented on [Tue Nov 07 2017](https://github.com/datahq/frontend/issues/128#issuecomment-342441544)

@Mikanebu are these functional ("black box") tests or tests here in this library. Also the library has no API so i was wondering what APIs you meant ...?

---

@Mikanebu commented on [Tue Nov 07 2017](https://github.com/datahq/frontend/issues/128#issuecomment-342442377)

@rufuspollock not for this library, all API from metastore, rawstore  and so on. Probably it should go to `pm` repo

---

@rufuspollock commented on [Tue Nov 07 2017](https://github.com/datahq/frontend/issues/128#issuecomment-342443228)

@Mikanebu yes this issue should not be here. Can you move it please (use the move issue button on the side).

**Comment by Mikanebu** [comment]
FIXED, tests are located in frontend-functional-tests repo https://github.com/datahq/frontend-functional-tests, it is also automated by Travis, and runs daily with frontend tests.
