### ISSUE TITLE
[EPIC] Private Datasets

### ISSUE THREAD

**Issue by zelima** [datahq/pm#59]
As a Publisher i want to have my dataset be private when I publish it so that no-one else can access it but me

* From CLI or other publishing mechanisms

As a Publisher I want to make my private dataset public (or unlisted) so that I can share it with others

* From Web UI preferably and secondarily from the CLI

As a Publisher I want to make public (or unlisted) dataset private so that it is hidden

* From the Web UI preferably and then from CLI

General

* Only owner can make these changes

## Acceptance Criteria

* [ ] able to set findability to Private for datasets via CLI
* [ ] ~~able to update dataset findability from web (ot other) UI~~

## Tasks

* [x] Phase I - set privacy via CLI (re run pipeliens) - `data push --findability=private`
  * [x] Do analysis 
  * [x] CLI supports including findability in creating presigned POST URLs   https://github.com/datahq/datahub-cli/issues/201
  * [ ] CLI handles writing presigned URLs  is source spec for assembler https://github.com/datahq/datahub-cli/issues/202
  * [x] Bitstore handles saving raw data under private ACL https://github.com/datahq/bitstore/issues/16
  * [x] Bitstore API for generating presigned URLs  https://github.com/datahq/bitstore/issues/17
    * [x] handles pkgstore as well https://github.com/datahq/bitstore/issues/18
  * [x] Assembler/planner/dpp-aws - processor for updaAsting object ACL https://github.com/frictionlessdata/datapackage-pipelines-aws/issues/10
  * [x] Frontend - request signed urls to display Private datasets https://github.com/datahq/frontend/issues/129
  * [x] BBTests updates in assembler https://github.com/datahq/assembler/issues/67
  * [ ] release CLI

Questions:

* What happens to previous revisions of the dataset (do they get hidden at the same time)?
  * That means re-running old flows ...
  * ??

### Phase I - Change dataset privacy via CLI only 
* services to make changes
  * bitstore -> Handle private ACL
  * CLI -> send findability as part of metadata
  * assembler (planner) -> set ACL according to findability for `dump.to_s3`
  * Frontend -> request pre-signed URL for the main datapckage.json from served API, instead of being hardcoded
  * metastore, for now, remains same as on every push will be re-exported with same ID and modified findability

`data push --findability=private`

#### CLI

We need to know that dataset is private: https://github.com/datahq/datahub-cli/blob/master/lib/utils/datahub.js#L152

```javascript=
// CLI
const body = {
      metadata: {
        owner: this._ownerid,
        findability:  this._findability
      },
      filedata: fileData
    }

const res = await this._fetch('/rawstore/authorize', token, {
      method: 'POST',
      body
    })
```

#### Bitstore

Put raw data on S3 under `private` ACL (according to findability sent by CLI)

```python
# Bitstore
def authorize(auth_token, req_payload):
    owner = req_payload.get('metadata', {}).get('owner')
    findability = req_payload.get('metadata', {}).get('findability', 'unlisted')

    s3headers = {
        'acl': 'private' if findability=='private' else 'public-read',
        'Content-MD5': file['md5'],
        'Content-Type': file.get('type', 'text/plain')
            }
    post = s3.generate_presigned_post(
        Bucket=config['STORAGE_BUCKET_NAME'],
        Key=s3path,
        Fields=s3headers)
  ...
```

Q: how can assembler read data from bitstore when it is private?

A: Think we should serve the API that takes URL, JWT and owner as query parameters (or send URL and owner via body and token as header) and returns signed URL (that will be used in source-spec)

Eg: api.datahub.io/rawstore/checkurl?url=https://rawstore.datahub.io/core/finance-vix&owner=core&jwt=token

```python=
def check_url(token, owner, url):
  needs_signed_url = requests.get(url)
  if needs_signed_url.status_code != 403:
    return {url: url}
  if owner is None:
    return Response(status=400)
  if not services.verify(token, owner):
    return Response(status=401)
  parsed_url = requests.utils.urlparse(url)
  bucket = parsed_url.netloc
  key = parsed_url.path
  signed_url = s3.generate_presigned_url(
    ClientMethod='get_object',
    Params={
        'Bucket': bucket,
        'Key': key
    }
  return {url: signed_url}
```

#### Assembler/planner

We need to export processed output on s3 (pkgstore) with `private` ACL as well https://github.com/datahq/planner/blob/master/planner/utilities.py#L24
```python
# planner
...
acl = 'private' if findability=='private' else 'public-read',
dump.to_s3,
   {
       'force-format': False,
       'handle-non-tabular': handle_non_tabular,
       'add-filehash-to-path': True,
       'bucket': os.environ['PKGSTORE_BUCKET'],
       'path': '/'.join(str(p) for p in parts),
       'acl': acl
   }
  ...
```

Q: how can assembler list the object in pkgstore if it's private?

A: it can't. 

Solution: Maybe instead of setting ACL while `dump.to_s3` we can dump them as public and add new processor (probably in dpp-aws) that will be run after all processors are executed, list all keys for dataset and changes ACL to `private`

```python=
# new processor
from datapackage_pipelines.wrapper import process

def modify_datapackage(dp, parameters, stats):
  s3 = boto3.client('s3')
  bucket = parameters['bucket']
  key = parameters['path'] # aka dataset
  acl = parameters['acl']
  objs = s3.list_objects_v2(Bucket=bucket, Prefix=key)
  for obj in objs:
    s3.put_object_acl(
    Bucket=bucket,
    Key=obj,
    ACL=acl)
  return dp

process(modify_datapackage=modify_datapackage)
```

#### Serve API for pkgstore signed urls

We need to generate Pre-signed URLs and probably serve new API for user/frontend to be able to read private objects.

We can create new service or maybe worth to refactor bitsotre to accept service (rawstore/pkgstore) and reuse `rawstore/checkurl` 

```Python
# New service/API Eg api.datahub.io/pkgstore

def get_signed_url(token, url):
  authenticate()
  bucket = url.get_base().replace('https://', '')
  key = url.get_tail()
  signed_url = s3.generate_presigned_url(
    ClientMethod='get_object',
    Params={
        'Bucket': bucket,
        'Key': key
    }
  return signed_url
)

```

#### Frontend 

To get the datapackage.json for showcase page we need to generate signed URL for it - we can use API bitstore API (or new service from above)

Besides that URLs inside that dp.json for resource are private as well so we need to generate signed urls for them as well. Again we can reuse API from above to get signed URLs on demand. 

https://github.com/datahq/frontend/blob/master/lib/index.js#L82

```javascript=
async getPackageFile(ownerid, name, path = 'datapackage.json') {
    const url = urllib.resolve(this.bitstoreUrl,
        [ownerid, name, 'latest', path].join('/')
        )
    const signed_url = await fetch(`api.datahub.io/pkgstore/signe_url?url={url}`)
    const response = await fetch(signed_url)
    return response
  }
```

Same logic when requesting resource urls (preview, download, other...)

---
Below is obsolete

~~* new processor in dpp-aws `update_with_signed_url` 
  * has access to bucket and keys
* new processor in assembler `update_with_signed_url` 
  * Probably should hit API above 
    * What to do with authenticatin?~~  
```python
# new processor in assembler

from datapackage_pipelines.wrapper import process

def modify_datapackage(dp, parameters, stats):
    for resource in dp[resources]:
        resource['path'] = api.datahub.io/pkgstore/signe_url?url=resource['path']
    return dp

process(modify_datapackage=modify_datapackage)
```

Q: What to do about URLs getting expired in max 7 days?
A: this is not any more problem as presigned urls are generated on demand (on every request)

**Comment by akariv** [comment]
Review - need to address these issues:
- How will assembler be able to read data from rawstore if it’s private.
- How will assembler be able to list objects in pkgstore if it’s private
- Frontend - how will the user be able to download resources from pkgstore. As presigned urls have an expiry time, they cannot be part of the datapackage, but need to be generated on demand. 
Probably should use the sign-url API to sign the resource urls as well.
- Use the sign-url only when needed (i.e. dataset is private).
- What about other ACLs (list objects in bucket) - need to make sure these are removed from bucket by default

Only missing thing (I think):
- Add to planner/assembler a new processor to list all objects for dataset and change ACLs according to the latest findability settings.
