### ISSUE TITLE
Migrate/create datasets for redirections from old datahubio to new one

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#62]
As an Admin I want to implement the internal redirects so that people get best experience by finding high quality datasets on datahub.io

This is a second part of https://github.com/datahq/pm/issues/20
Also follow up to #11 

## Acceptance criteria

* [ ] All selected "old" datahub.io items are migrated/created in new datahub.io and redirected

## Tasks

* [ ] Create new datasets needed
  * [ ] do analysis how we do it
  * [ ] Implement
* [ ] Implement these redirects

**Comment by zelima** [comment]
@Mikanebu think this one is now FIXED. Can you confirm and close?

**Comment by Mikanebu** [comment]
@zelima I am not sure that this is FIXED, because we have not created any datasets. Only created redirects. I think it needs a proper analysis on which datasets we will create

**Comment by zelima** [comment]
@Mikanebu do we have 
* A list of all dataset that exists on old datahub?
* A list of the datasets that are redirected to new datahub?

The difference is what we need right?

**Comment by Mikanebu** [comment]
@zelima Yes, we have a traffic analysis spreadsheet and list of datasets to be implemented
