### ISSUE TITLE
Electron app - new features

### ISSUE THREAD

**Issue by zelima** [datahq/pm#64]
TODO: User Stories 

## Acceptance Criteria

TODO

## Tasks

* [ ] Research & implementation of Electron apps testing
* [ ] Login
* [ ] Push (publish) a dataset
* [ ] Showcase prior pushing
* [ ] Table Schema editor + validation info

## Analysis

TODO

**Comment by anuveyatsu** [comment]
DUPLICATE
