### ISSUE TITLE
Electron app new features (4 Dec Sprint)

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#65]
*This is an Epic for having all new features issues for desktop app*

* [x] showcase page prior pushing - https://github.com/datahq/data-desktop/issues/6
* [x] implement login - https://github.com/datahq/data-desktop/issues/7
* [x] uploading (pushing) data - https://github.com/datahq/data-desktop/issues/8
* [x] table schema editor - https://github.com/datahq/data-desktop/issues/15

**Comment by anuveyatsu** [comment]
FIXED - see appropriate issues for more details.
