### ISSUE TITLE
Pricing page and plans 

### ISSUE THREAD

**Issue by zelima** [datahq/pm#67]
As a Publisher i want to know what it would cost to store my data so that I can make an informed choice to use you (or not)

As a Publisher I want to know you are a sustainable business so that I have confidence you will be around in the future so that if i rely on you and invest time in using you that will be worth it

As a Consumer I want to know how much datasets cost (or if they are for free) so they can work out if I want to use them

## Acceptance Criteria 

* [x] Pricing page exists with plans and its prices
* [x] Users/publishers are assigned to the  plans

## Tasks

* [x] Draft pricing page
* [x] Assign users to a plan

**Comment by rufuspollock** [comment]
FIXED. for now we're doing the actual plan allocation by hand.

**Comment by zelima** [comment]
@rufuspollock clicking the sign-up button results in opening a Email dialog box
