### ISSUE TITLE
Get a suite of "bad" data ...

### ISSUE THREAD

**Issue by Mikanebu** [datahq/pm#7]
We want to check our platform in the following cases:
* datapackage.json that is not correct json
* invalid  datapackage.json
* Upload with bad csv - what happens
  * different encoding
  * delimiter
* Upload with other stuff
  * `.txt`
  * `.xlsx`

## Acceptance criteria 
* [x] created directories for each example
* [x] run `data push` for each example
* CLI - does it error out
* System (we would probably have to disable the CLI checks to be able to see this)
  * e.g. push invalid datapackage.json
    * and see how quickly we get an error in frontend
    * Do we run the entire pipeline?

## Tasks

* [x] Locate or create these examples in `qa-data` directory
* [x] Test using CLI
* [x] System(without CLI checks and normalizations)
  * [x] run `data push` for each case
    * [x] How quickly we can get error in frontend
    * [ ] Do we run entire pipeline?

**Comment by Mikanebu** [comment]
QA report can be found in the following link:
https://hackmd.io/EYTgxg7CCGwCYFoBsAzC0EBZMEYcIA44J8kBTCMgVgCZoww5hog=?both#qa-testing-report

**Comment by Mikanebu** [comment]
FIXED
