### ISSUE TITLE
Electron app new features (18 Dec sprint)

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#72]
*Electron app related items for this (18 Dec) sprint will be added here*

* [x] analytics tracking - https://github.com/datahq/data-desktop/issues/16
* [x] Add options on push: public, hidden, private (with descriptions) - https://github.com/datahq/data-desktop/issues/17
* [x] After publishing a dataset user should be logged in on the website (by coming from the app) - https://github.com/datahq/data-desktop/issues/18
* [ ] Research windows / linux (?) - what would it take - https://github.com/datahq/data-desktop/issues/19
* [ ] research and analysis re testing - https://github.com/datahq/data-desktop/issues/9
* [ ] use datahub logo in svg - https://github.com/datahq/data-desktop/issues/20
* [x] ~~Feedback option in the app - https://github.com/datahq/data-desktop/issues/21~~ - leave for later

**Comment by zelima** [comment]
Moving to next milestone as some research still needed

**Comment by zelima** [comment]
WONTFIX/OBSOLETE this feature is no longer maintained. It exists as is
