### ISSUE TITLE
Automate publication to npm for 2-3 datasets

### ISSUE THREAD

**Issue by rufuspollock** [datahq/pm#80]
Top level: as a JS/node user i want to import core data into my app natively using the node / js package manager so that I don't have to learn any new tool and i get great data easily.

We have done one dataset by hand. Automate what we did by hand and extend to another 1-2 popular dataset e.g. `country-codes` `currency-codes`.

## Acceptance criteria

* [x] script for automating generation of node branch
* [x] 1-2 more datasets on npm

TODO: @Mikanebu proper analysis.

## Tasks

* [x] proper analysis
* [x] prepare `country-codes`
* [x] prepare `currency-codes`
* [x] update `travis.yml` to publish automatically on npm

## Analysis

Since we have created a script with the methods and included `json` version for data itself. There are some parts need to be done manually. 

* Manual work
  * create a script with methods to get data
  * create `json` version of data(can be downloaded from datahub.io)
  * updated `README.md` with usage

* Automation
  * update `travis.yml` to create new branch and keep it up to date with master
  * auto-publish to npm

* Datasets to be added into npm
  * country-codes
  * currency-codes

* For publishing to `npm` we will use separate branch

**Comment by anuveyatsu** [comment]
@Mikanebu do you think we need to create a script  for getting data like we did for country-list dataset? I suppose just letting people to import JSON version of dataset from NPM is good enough so they can work out what they need from that point.

**Comment by Mikanebu** [comment]
@anuveyatsu ok, when we implemented with @AcckiyGerman we thought it would be nice to have methods to get data... But I think, just providing `json` would be enough for these datasets. In `country-codes` there will be too many methods to cover all cases...

**Comment by AcckiyGerman** [comment]
We created those methods for the backward compatibility (the original npm package had them).
There is no need of those methods in new packages I think.

**Comment by Mikanebu** [comment]
`Country-codes` is live https://www.npmjs.com/package/@datasets/country-codes

**Comment by Mikanebu** [comment]
`Currency-codes` is live https://www.npmjs.com/package/@datasets/currency-codes

**Comment by rufuspollock** [comment]
@Mikanebu :clap: - can you document how this is automated and where. A big goal here was to automate the process rather than do this by hand (or at least learn how to do that).

/cc @akariv

**Comment by Mikanebu** [comment]
I cannot to fully automate as I mentioned in my analysis. For now I published `country-codes` and `currency-codes` manually.

**Comment by zelima** [comment]
Moving this to the backlog for now, as it remains untouched.

@Mikanebu could you please describe what exactly is the blocker here? I do not see anything explaining that in the analysis section.

**Comment by anuveyatsu** [comment]
FIXED for:

- https://github.com/datasets/country-list
- https://github.com/datasets/country-codes (awaiting to merge the PR)
- https://github.com/datasets/currency-codes

**Comment by anuveyatsu** [comment]
Closing it as FIXED now. We're only waiting for https://github.com/datasets/country-codes/pull/68 to be merged.
