### ISSUE TITLE
Old dataset that never successfully "built" appear in search 

### ISSUE THREAD

**Issue by zelima** [datahq/pm#81]
If you visit search page and click on around first 10 packages all of them will result in 404. Those are older packages that do not have any successful revisions. 

## Acceptance Criteria 

* [ ] no metadata exists in search DB if dataset failed to build
* [ ] If dataset is in search clicking it should result with nice showcase page

## Tasks 

* [ ] Identify brocken datasets (make list)
* [ ] delete from ElastiSearch manually (???)

**Comment by zelima** [comment]
Issue moved to [datahq/metastore #21](https://github.com/datahq/metastore/issues/21) via [**ZenHub**](https://www.zenhub.com/)
