### ISSUE TITLE
Study automation for Dima

### ISSUE THREAD

**Issue by AcckiyGerman** [datahq/pm#86]
As a datahub developer I want to know how does the automation works under the hood, so I would able to (use / improve / make docs for) automation.

## Acceptance criteria
* [ ] @acckiygerman is able to automate datasets and understands the automation under the hood

## Tasks
* [x] understand how the automation works [2d] + 30% (improve estimation due to estimations analyse)
    * [x] read flow spec part of planer README https://github.com/datahq/planner [1.5h]
    * [x] read docs for https://github.com/frictionlessdata/datapackage-pipelines [4h]
    * [x] flow.yaml: learn examples (finance-vix, bonds UK, bonds USA), try to run it [4h]
    * [x] read the https://github.com/datahq/datahub-cli code to understand `data push-flow` [4h]
    * [x] run `data push-flow` with different datasets, see the workflow, errors, etc [3h]

## Analyse

After this task, start https://github.com/datahq/pm/issues/84 , then https://github.com/datahq/pm/issues/85

**Comment by zelima** [comment]
@AcckiyGerman if you add up those estimates they sum up to 17 hours, but the issue is estimated 24, why? 
Also, don't think you need that much understanding of dpp (datapackage-pipelines). Just see what processors available and try out several of them according to their examples.

**Comment by AcckiyGerman** [comment]
@zelima Initially overall time was ~2d then I added extra 30% and now it is 3d (24h)
Actually it is quite hard to predict how much time the doc learning will take, so estimations for this task could not be precise with my estimation skills :)
Hope my technical tasks are estimated more precisely.

**Comment by rufuspollock** [comment]
@AcckiyGerman personally i don't think this should be its own issue - you understanding something should be part of the whatever issue you need that knowledge for e.g. #85. I also think if you do have this the acceptance criteria should include some output like a short write-up or diagram.

**Comment by AcckiyGerman** [comment]
Ok, I will merge this two, and add an outcome to acceptance, thanks for
feedback.

**Comment by AcckiyGerman** [comment]
FIXED
Merged with https://github.com/datahq/pm/issues/85
Added outcome (automation guide)
