### ISSUE TITLE
Datasets need to be removed from search

### ISSUE THREAD

**Issue by Mikanebu** [datahq/pm#92]
We want to remove invalid, test datasets from search, so users can see only valid, high quality datasets.

## Acceptance criteria

* [x] Invalid datasets removed from search

## Tasks

* [x] List of all datasets that need to be removed
* [x] remove
* [x] check on website

## Analysis

List of datasets need to be removed from search: 

* [x] http://datahub.io/zelima/simple-graph-spec

* [x] http://datahub.io/zelima1/vix-zip-testing
* [x] http://datahub.io/zelima1/vega-views-tutorial-grouping
* [x] http://datahub.io/zelima1/vix-zip
* [x] http://datahub.io/zelima1/finance-vix

* [x] http://datahub.io/anuveyatsu/farm-survey-simple
* [x] http://datahub.io/anuveyatsu/sample-2sheets-chatty-baboon-56
* [x] http://datahub.io/anuveyatsu/sample-2sheets-popular-cougar-90
* [x] http://datahub.io/anuveyatsu/sample-simple-rotten-snake-18
* [x] http://datahub.io/anuveyatsu/sea-level-rise
* [x] http://datahub.io/anuveyatsu/sample-2sheets-sweet-bobcat-23
* [x] http://datahub.io/anuveyatsu/sample-simple-ordinary-lionfish-12
* [x] http://datahub.io/anuveyatsu/sample-terrible-puma-8
* [x] http://datahub.io/anuveyatsu/co2-ppm
* [x] http://datahub.io/anuveyatsu/gdp
* [x] http://datahub.io/anuveyatsu/sample-2sheets-mighty-husky-89
* [x] http://datahub.io/anuveyatsu/sample-2sheets-chatty-bobcat-26
* [x] http://datahub.io/anuveyatsu/sample-simple-friendly-vampirebat-33
* [x] http://datahub.io/anuveyatsu/sample-silent-bobcat-20
* [x] http://datahub.io/anuveyatsu/sample-2sheets-great-impala-86
* [x] http://datahub.io/anuveyatsu/sample-simple-splendid-warthog-16
* [x] http://datahub.io/anuveyatsu/sample-2sheets-good-yak-61
* [x] http://datahub.io/anuveyatsu/sample-2sheets-cuddly-parrot-79
* [x] http://datahub.io/anuveyatsu/test-uk-gov-petitions
* [x] http://datahub.io/anuveyatsu/sample-simple-curly-dolphin-20
* [x] http://datahub.io/anuveyatsu/sample-lucky-lionfish-63
* [x] http://datahub.io/anuveyatsu/sample-2sheets-serious-crab-66
* [x] http://datahub.io/anuveyatsu/sample-cuddly-cat-100
* [x] http://datahub.io/anuveyatsu/sample-curvy-lion-75
* [x] http://datahub.io/anuveyatsu/sample-2sheets-blue-eagle-55
* [x] http://datahub.io/anuveyatsu/sample-2sheets-average-wasp-63
* [x] http://datahub.io/anuveyatsu/airbnb-sample-tame-bobcat-84
* [x] http://datahub.io/anuveyatsu/sample-pink-dragon-77
* [x] http://datahub.io/anuveyatsu/sample-clever-lion-60
* [x] http://datahub.io/anuveyatsu/farm-survey-simple
* [x] http://datahub.io/anuveyatsu/sample-2sheets-chatty-baboon-56
* [x] http://datahub.io/anuveyatsu/sample-2sheets-popular-cougar-90
* [x] http://datahub.io/anuveyatsu/sample-simple-rotten-snake-18
* [x] http://datahub.io/anuveyatsu/test-select
* [x] http://datahub.io/anuveyatsu/finance-vix

* [x] http://datahub.io/anuar.ustayev/euribor
* [x] http://datahub.io/anuar.ustayev/corruption-perceptions-index

* [x] http://datahub.io/meiran1991@gmail.com/invalid-data-encoding
* [x] http://datahub.io/meiran1991@gmail.com/invalid-data-xlsx
* [x] http://datahub.io/meiran1991@gmail.com/datapackage
* [x] http://datahub.io/meiran1991@gmail.com/invalid-data-delimiter
* [x] http://datahub.io/meiran1991@gmail.com/transform-example-gdp-uk
* [x] http://datahub.io/Mikanebu/push-speed-00
* [x] http://datahub.io/Mikanebu/bond-yields-us-10y
* [x] http://datahub.io/Mikanebu/gdp-us
* [x] http://datahub.io/Mikanebu/vega-views-tutorial-lines
* [x] http://datahub.io/Mikanebu/push-speed-8
* [x] http://datahub.io/Mikanebu/gdp-uk
* [x] http://datahub.io/Mikanebu/israel_traffic_violations
* [x] http://datahub.io/Mikanebu/co2-ppm
* [x] http://datahub.io/Mikanebu/bond-yields-uk-10y

* [x] http://datahub.io/rufuspollock1/mydata-modern-fly-44

* [x] http://datahub.io/svetozarstojkovic/exchange-rates

* [ ] These datasets are unlisted. but would be great to remove
  * [ ] https://datahub.io/core/interest_rates-gb
  * [ ] https://datahub.io/core/us-employment
  * [ ] https://datahub.io/core/us-employment-bls

* [x] MachineLearning datasets, since we change username to `machine-learning`
  * [x] http://datahub.io/MachineLearning/cervical-cancer
  * [x] http://datahub.io/MachineLearning/fertility
  * [x] http://datahub.io/MachineLearning/seismic-bumps
  * [x] http://datahub.io/MachineLearning/breast-cancer
  * [x] http://datahub.io/MachineLearning/primary-tumor

**Comment by zelima** [comment]
FIXED
