### ISSUE TITLE
Support emojis in markdown

### ISSUE THREAD

**Issue by rufuspollock** [datahq/pm#93]
As a Developer, I want to be able to use emojis when creating content for DataHub in markdown so that my writings have more interactivity and look better.

## Acceptance criteria

* [x] all emojis in https://datahub.io/awesome/football rendered as expected

## Tasks

* [x] research modules for our markdown processor and select the best one
* [x] add the module in the md processor
* [x] test
* [x] deploy

## Analysis

Available NPM packages:

* https://github.com/emojione/emojify.js
* https://github.com/markdown-it/markdown-it-emoji
* https://github.com/omnidan/node-emoji
* ~~https://github.com/tallesl/node-emojis~~ - only 6 stars while others have a lot
* ~~https://github.com/Kikobeats/emojis-list~~ - not so popular + last updated 2y ago

~~Remaining 2 candidates are both good enough. Node-emoji is more popular and looks like easy-to-use for general purposes. However, markdown-it-emoji is designed specifically for markdown-it processor. Therefore, we choose markdown-it-emoji library as we want to have the quickest and simpliest way of implementing it.~~

We want to support same list of emojis as Gitter or Github. For that reason we decided to use the same emojifier as Gitter - https://github.com/emojione/emojify.js

To be even more specific we will use Gitter's fork of emoji.js - https://github.com/gitterHQ/emojify.js by simply copying over the main module + images.

**Comment by anuveyatsu** [comment]
FIXED
