### ISSUE TITLE
Blog post about automated core datasets

### ISSUE THREAD

**Issue by zelima** [datahq/pm#95]
As the datahub admin, I want to announce about automated datasets to the community so that people are aware and can benefit from it.

We are on the way to publish some core datasets in auto mode, regularly (see #85 and #84). Once this is done we need blog post about them. We also have automated some of the datasets via Travis-CI by running python or other scripts on a schedule. All automated datasets should be indicated in this list (see the `auto_publish` column): https://github.com/datasets/registry/blob/master/core-list.csv

## Acceptance Criteria 

* [x] Blog post is live and includes links to the automated datasets

## Tasks

* [x] create a structure of the post
* [x] write a draft
* [x] get a review from Esteban
* [x] improve per review
* [x] publish and deploy

**Comment by zelima** [comment]
@AcckiyGerman is this PR related to this issue? https://github.com/datahq/frontend/pull/188

**Comment by AcckiyGerman** [comment]
The issue goal is a blog-post like 'we have a cool automated datasets - yahoo!' (isn't it?) and the #188 PR is a technical giude how to automate.
Of course we'll include a link to the automation guide in the future blog-post, however I'm not sure if we need this blogpost now.

**Comment by AcckiyGerman** [comment]
Also, @rufuspollock mentioned that it would be cool to write a **"all broken core datasets particularly story about how much work it is to keep them working"** - so may be we just rename this current issue and update its goals.

**Comment by zelima** [comment]
@AcckiyGerman ok, as we decided to hold on automation, moving this in backlog for now

**Comment by anuveyatsu** [comment]
@zelima I'm going to write a blog post about automatically updated datasets on Datahub. However, the automation must not be done via the DataHub flow system, it also can be done via Travis-ci. E.g., this one can be counted as automated - https://github.com/datasets/oil-prices - where we just run a python script on Travis and cronjob is scheduled to run on the weekly basis. Wdyt?

**Comment by zelima** [comment]
@anuveyatsu Agree. Think that flow covers the topic

**Comment by anuveyatsu** [comment]
@zelima great, I will update the issue's description then.

**Comment by anuveyatsu** [comment]
FIXED - https://datahub.io/blog/automatically-updated-core-datasets-on-datahub
